export interface GuiaCirurgico {
  especialidade: string;
  nome: string;
  tempos: string;
  tecnica: string;
  problemas: string;
  correcoes: string;
  posOp: string;
  referencias: string;
}

export const ESPECIALIDADES = [
  'Cirurgia Cardíaca',
  'Urologia',
  'Cirurgia Torácica',
  'Ortopedia',
  'Otorrinolaringologia',
  'Neurocirurgia',
  'Ginecologia',
  'Oftalmologia',
  'Cirurgia Plástica',
  'Cirurgia Vascular',
] as const;

export type Especialidade = typeof ESPECIALIDADES[number];

export const BANCO_CIRURGIAS: GuiaCirurgico[] = [
  // ── CIRURGIA CARDÍACA ──────────────────────────────────────
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Revascularização do Miocárdio (CRM) com CEC',
    tempos: '1. Esternotomia; 2. Dissecção de enxertos; 3. Heparinização; 4. CEC; 5. Clampeamento/anastomoses; 6. Saída CEC; 7. Protamina.',
    tecnica: 'Geral Balanceada/TIVA (MYRIAD Trial 1A). ETE obrigatório (SCA/ASA). Indução: Etomidato 0,2–0,3 mg/kg + Fentanil 5–10 mcg/kg + Propofol ou Midazolam. Manutenção: Sevoflurano 0,5–1,5 MAC ou Propofol 4–8 mg/kg/h em TIVA. Relaxamento com Cisatracúrio ou Rocurônio. Monitorização: PAI em punho radial direito, CVC, ETE, NIRS cerebral bilateral, débito urinário contínuo. Temperatura: Hipotermia moderada na CEC (32–34 °C). Heparinização: 300–400 UI/kg, TCA > 480 s antes de iniciar CEC.',
    problemas: 'Vasoplegia Pós-CEC por SIRS (refratária a catecolaminas); Resposta simpática intensa à esternotomia (hipertensão/taquicardia); Coagulopatia por diluição/CEC; Espasmo de enxerto de artéria mamária (LIMA); Infarto perioperatório (nova disfunção de parede ao ETE); Embolia gasosa coronária/cerebral; Hiperglicemia induzida pela CEC e circulação extracorpórea.',
    correcoes: 'Vasoplegia: Noradrenalina (0,05–0,5 mcg/kg/min) ± Vasopressina 0,04 UI/min ± Azul de Metileno 1,5–2 mg/kg IV lento se refratário. Esternotomia: bólus Remifentanil 1 mcg/kg ou aprofundar anestesia. Coagulopatia: guiado por ROTEM/TEG (Fibrinogênio se amplitude baixa → Crioprecipitado; Plaquetas se lise; Ácido Tranexâmico 1 g profilático antes da incisão). Espasmo LIMA: Papaverina tópica, Verapamil intraluminal 0,1 mg/mL. Reversão de Heparina: 1 mg Protamina/100 UI Heparina, infundir lentamente para evitar hipotensão.',
    posOp: 'ERAS Cardiac: Extubação precoce na UTI (<6 h), alvo SpO2 > 94% com oxigênio nasal. Analgesia multimodal: Bloqueio ESP bilateral (T4–T5) com Ropivacaína 0,25% ecoguiado + Paracetamol 1 g/6 h + Cetorolaco 15–30 mg se sem contraindicação renal. Deambulação no 1º dia pós-op. Critérios de alta UTI: hemodinâmica estável, débito de drenos < 100 mL/h, paciente extubado e colaborativo, sem aritmias ativas.',
    referencias: 'Engelman et al., 2019 (ERAS Cardiac Society Guidelines). Habib et al., ESC/EACTS Guidelines on Myocardial Revascularization 2018. Ferraris et al., STS Blood Conservation Guidelines.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Substituição/Reparação Valvular e TAVI',
    tempos: 'TAVI: 1. Acesso vascular; 2. Rapid Pacing; 3. Implante. Aberta: 1. Esternotomia; 2. CEC; 3. Troca valvar.',
    tecnica: 'TAVI: MAC/Sedação Consciente (SOLVE-TAVI). Aberta: Geral com ETE 3D.',
    problemas: 'Hipotensão grave (miocárdio isquêmico); BAV total no TAVI.',
    correcoes: 'Manter FC 60–70 bpm (Fenilefrina). Rapid Pacing: Adrenalina se parada refratária.',
    posOp: 'Observação UTI. Alta precoce (1–3 dias) para TAVI.',
    referencias: 'Otto et al., ACC/AHA Valvular Guidelines 2020.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Correção de Aneurisma da Aorta (Aberta e TEVAR)',
    tempos: 'TEVAR: Acesso femoral, endoprótese. Aberta: Esternotomia, CEC com Hipotermia Profunda, Tubo Dacron.',
    tecnica: 'TEVAR: Regional (peridural torácica), MAC ou Geral com IOT conforme risco/anatomia. Aberta: Geral complexa com indução cuidadosa (Etomidato preferido se FE reduzida), NIRS cerebral bilateral obrigatório, PAI radial direita + femoral, CVC, DPCA contínuo (débito cardíaco). Hipotermia profunda circulatória (DHCA 18 °C) para aorta ascendente complexa. Drenagem de LCR: cateter lombar 14G inserido na véspera, manter pressão ≤ 10 mmHg.',
    problemas: 'Isquemia Medular (Paraplegia — incidência 3–8% na aorta toracoabdominal); Vasoplegia e Sangramento Maciço na CEC; Lesão renal aguda por isquemia e contraste; Embolia cerebral durante manipulação do arco aórtico; AVC isquêmico; Dissecção retrógrada pós-TEVAR; Coagulopatia de consumo e fibrinólise.',
    correcoes: 'Dreno de LCR: manter débito máximo 10–15 mL/h para pressão ≤ 10 mmHg (se menor, fechar parcialmente para evitar hematoma subdural). Paraplegia identificada no pós-op: drenagem imediata, PAM alvo ≥ 80–90 mmHg, considerar re-implante de intercostais. Protocolo transfusão maciça (1:1:1 CH:PFC:Plaquetas) guiado por TEG/ROTEM. Proteção renal: Manitol 12,5 g antes do clampe, manter euvolemia, evitar contraste nefrotóxico. Embolia cerebral: perfusão cerebral seletiva anterógrada durante DHCA.',
    posOp: 'Monitorização neurológica horária de extremidades inferiores (força, sensibilidade). UTI por 48–72 h mínimo. Manter PAM 80–90 mmHg no pós-op precoce para perfusão medular. Extubação precoce somente após avaliação neurológica completa. Vigilância de sangramento tardio em drenos e acesso femoral/axilar. Analgesia: Peridural torácica (se inserida) com Ropivacaína 0,1% + Fentanil; alternativa PCA endovenosa.',
    referencias: 'Isselbacher et al., 2022 ACC/AHA Aortic Disease Guidelines. Etz et al., Spinal cord protection for aortic surgery. J Thorac Cardiovasc Surg 2019. Conrad et al., Prevention of spinal cord injury in thoracoabdominal aortic aneurysm repair.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Cirurgia de Cardiopatias Congênitas (ex: Fallot)',
    tempos: '1. Esternotomia; 2. CEC; 3. Ressecção de obstruções e fechamento de CIV; 4. Saída de CEC.',
    tecnica: 'Indução inalatória/venosa. Evitar bolhas de ar nos acessos (risco de embolia paradoxal).',
    problemas: 'Crise de Hipóxia (Spells); Disfunção Aguda de VD pós-CEC.',
    correcoes: 'Crises: FiO2 100%, volume, Fenilefrina. Evitar inotrópicos que espasam o VD. VD falido: Milrinona e iNO.',
    posOp: 'UTI Pediátrica. Analgesia com parasternal block.',
    referencias: 'Stout et al., 2018 AHA/ACC Congenital Heart Disease.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Transplante Cardíaco Ortotópico',
    tempos: '1. Reesternotomia; 2. CEC; 3. Cardiectomia; 4. Anastomoses; 5. Reperfusão.',
    tecnica: 'Indução cautelosa preservando estabilidade (Etomidato/Fentanil). ETE.',
    problemas: 'Coração Denervado (sem resposta vagal); Falência primária do enxerto de VD.',
    correcoes: 'Bradicardia: Agonistas diretos (Isoproterenol 0,01–0,05 mcg/kg/min) ou marcapasso. Proteção VD com hiperventilação leve e iNO.',
    posOp: 'Isolamento reverso estrito. Imunossupressão.',
    referencias: 'ISHLT Guidelines for heart transplant recipients.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Cirurgia para Arritmias (Procedimento de Maze)',
    tempos: '1. Linhas de ablação (crio/RF) em veias pulmonares; 2. Exclusão de auriculeta; 3. Cirurgia valvar base.',
    tecnica: 'Geral com ETE obrigatório para avaliar trombos em apêndice atrial.',
    problemas: 'Lesão térmica do esôfago (fístula) ou nervo frênico; BAV total pós-ablação.',
    correcoes: 'Monitorização de temperatura esofágica contínua (<15 °C ou >39 °C → pausa). Marcapasso epicárdico de prontidão.',
    posOp: 'Telemetria em UTI. Manutenção de antiarrítmicos (Amiodarona).',
    referencias: 'Calkins et al., HRS/EHRA Consensus on Atrial Fibrillation.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Implantação de Dispositivos (Pacemakers e CDI)',
    tempos: '1. Punção venosa; 2. Passagem de eletrodos sob escopia; 3. Teste de limiar; 4. Confecção de loja.',
    tecnica: 'Sedação (MAC) com Propofol/Dexmedetomidina + Anestesia Local.',
    problemas: 'Teste de Desfibrilação (indução de FV); Pneumotórax; Tamponamento cardíaco.',
    correcoes: 'Aprofundar sedação antes do choque do CDI. Ter pás externas coladas. Pericardiocentese se tamponamento.',
    posOp: 'Raio-X de tórax pós-operatório. Restrição de movimento do braço.',
    referencias: 'Kusumoto et al., ACC/AHA Bradycardia Guidelines.',
  },

  // ── UROLOGIA ──────────────────────────────────────────────
  {
    especialidade: 'Urologia',
    nome: 'Ressecção Transuretral da Próstata (RTU-P)',
    tempos: '1. Litotomia; 2. Ressectoscópio; 3. Ressecção sob irrigação contínua.',
    tecnica: 'Raquianestesia T10 padrão-ouro: Bupivacaína hiperbárica 0,5% 10–12,5 mg + Fentanil 20 mcg intratecal. Vantagem: monitorização neurológica do paciente acordado — primeiro sinal de Síndrome RTU é confusão/agitação. Geral IOT como alternativa se contraindicação à raquianestesia ou tempo cirúrgico esperado > 90 min. Monitorização seriada de Sódio sérico a cada 30 min em ressecções longas.',
    problemas: 'Síndrome de RTU (intoxicação hídrica por glicina — hiponatremia dilucional, hipervolemia, hiperamonemia); Perfuração vesical extraperitoneal ou intraperitoneal (dor súbita em ombro se intraperitoneal); Hipotermia por irrigação fria; Bacteremia/Sepse por manipulação de uropatógenos; Coagulopatia pela liberação de ativador de plasminogênio da próstata; Conversão para cirurgia aberta por sangramento.',
    correcoes: 'Síndrome RTU: identificar na raqui (agitação, náusea, confusão) → interromper irrigação, Furosemida 20–40 mg IV, restricão hídrica rigorosa. Se Na⁺ < 120 mEq/L sintomático: NaCl 3% 100 mL IV em 20 min (não corrigir mais de 8 mEq/L por hora — risco mielinólise). Se > 120 assintomático: aguardar diurese espontânea. Perfuração intraperitoneal: conversão cirúrgica aberta. Extraperitoneal: drenagem contínua por sonda e suspender procedimento.',
    posOp: 'Anticolinérgicos (Oxibutinina 5–10 mg 8/8h) para espasmo vesical. Manter irrigação vesical pós-op se sangramento. Sonda de Foley 22–24 Fr por 24–48 h. Alta com orientações sobre hematúria esperada e sinais de alerta de Síndrome RTU tardia. Analgesia: Paracetamol + AINEs se função renal preservada.',
    referencias: 'EAU Guidelines on Non-Neurogenic LUTS 2023. Mebust et al., Transurethral prostatectomy: TURP syndrome. O\'Kelly et al., Fluid absorption during TURP.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Prostatectomia Radical (Robótica/Laparoscópica)',
    tempos: '1. Trendelenburg extremo (>30°); 2. Pneumoperitônio; 3. Exérese; 4. Anastomose.',
    tecnica: 'Geral IOT com indução padrão (Propofol + Fentanil ou Remifentanil + Rocurônio). Bloqueio neuromuscular profundo essencial durante todo o procedimento (PTC 0–1, TOF 0) para ampliar campo laparoscópico e reduzir pressão de pneumoperitônio (alvo < 12 mmHg). TIVA com Propofol infusão preferida pela menor incidência de NVPO e melhor recuperação cognitiva. Monitorização: PAI opcional (ASA III+), acesso periférico calibroso, sonda gástrica para descomprimir, Trendelenburg ≥ 30° com coxins suporte de ombro. Restrição hídrica severa: < 1,0–1,5 L totais até confecção da anastomose uretro-vesical.',
    problemas: 'Edema facial, lingual e de via aérea (Trendelenburg extremo e prolongado); Aumento de PIC e cefaleia pós-op; Redução de complacência pulmonar e atelectasias; Bradicardia vagal ao insuflar pneumoperitônio; Embolia gasosa por CO2; Lesão de vasos ilíacos ou nervo obturador; Fístula urinária por anastomose tensa se restrição hídrica desconsiderada; Retenção urinária pós-op.',
    correcoes: 'Edema de via aérea: elevar cabeceira > 30° ao final do caso, Leak Test (pressão 20–30 cmH2O) obrigatório antes de extubar; se vazamento ausente ou stridor → diferir extubação. Trendelenburg: interrupções periódicas (> 4 h de procedimento), PAM calculada para altura da cabeça. Embolia por CO2: posição Durant (lateral esquerdo + Trendelenburg), aspirar gás por CVC se parada cardíaca. Neurobloqueio: reverter com Sugammadex 2–4 mg/kg no final. Anastomose: manter diurese ≥ 0,5 mL/kg/h com bolus cuidadosos se necessário.',
    posOp: 'ERAS Pélvico: TAP block bilateral ecoguiado (Ropivacaína 0,25% 20 mL/lado) ou bloqueio de parede abdominal pré-peritoneal. Alta precoce alvo (D2–D3). Analgesia multimodal: Paracetamol 1 g/6 h + Celecoxibe 200 mg 12/12 h + Dipirona 1 g/8 h. Evitar opioides sistêmicos. Mobilização precoce no D1 pós-op. Manter sonda de Foley por 7–10 dias para proteção da anastomose.',
    referencias: 'Ljungqvist et al., ERAS Society Pelvic Surgery. Ficarra et al., Robot-assisted radical prostatectomy outcomes. Eur Urol 2012. Wuethrich et al., Extended PLND in robot-assisted RP. J Urol 2013.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Nefrectomia (Total ou Parcial)',
    tempos: '1. Posição de flanco; 2. Clampeamento hilar; 3. Ressecção.',
    tecnica: 'Geral Balanceada IOT. Indução padrão + Relaxamento com Rocurônio. Posicionamento lateral em quebra (kidney rest): verificar axila (coxim axilar), joelhos fletidos 30°, perna declive estendida, protetor de cabeça, ponto de apoio trocanteriano. Monitorização completa: PAI (se ASA III+), acesso periférico duplo. Nefrectomia parcial: planejar tempo de isquemia quente ≤ 25 min para preservar função remanescente.',
    problemas: 'Lesão isquêmica ao rim remanescente (parcial — tempo isquemia quente > 30 min eleva risco de IRA definitiva); Lesão de plexo braquial por tração do braço; Síndrome Compartimental de glúteos (lateral prolongado); Pneumotórax por lesão de pleura em nefrectomia retroperitoneoscópica; Lesão inadvertida de baço (esquerda) ou fígado (direita); Embolia por CO2 em laparoscópica; Crise hipertensiva intraoperatória em tumor de adrenal associado (feocromocitoma oculto).',
    correcoes: 'Proteção renal: Manitol 12,5–25 g IV 15–20 min antes do clampeamento isquêmico. Euvolemia estrita intraop. Isquemia quente > 25 min: comunicar cirurgião, avaliar desclampeamento temporário. Plexo braquial: coxim axilar correto, não permitir elevação do kidney rest sem verificar axila. Pneumotórax: aumento súbito de pressão de pico → checar USG pulmão → drenagem se necessário. Feocromocitoma suspeito: Fentolamina 1–5 mg IV ou Nitroprussiato de sódio para crises hipertensivas; Esmolol 0,5–1 mg/kg para taquicardia.',
    posOp: 'TAP Block subcostal ecoguiado (Ropivacaína 0,25% 20 mL), QLB posterior ou ESP Block T8–T9. Multimodal: Paracetamol 1 g/6 h + AINEs (se sem contraindicação) + Dipirona 1 g/8 h. Opioides de resgate apenas. Alta precoce (D2 laparoscópica). Monitorar função renal pós-op (creatinina D1 e D3 para parcial). ERAS: mobilização D0, dieta oral D1.',
    referencias: 'ERAS Society Radical Nephrectomy Guidelines 2022. Mir et al., ERAS in minimally invasive partial nephrectomy. Eur Urol 2020. Gill et al., Complications of laparoscopic nephrectomy.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Cirurgias de Cálculo (Ureterolitotripsia e NLPC)',
    tempos: 'Uretero: Litotomia, laser. NLPC: Prono, punção lombar percutânea, dilatação e litotripsia.',
    tecnica: 'Uretero: Raqui ou Geral. NLPC: Geral IOT obrigatória (decúbito prono).',
    problemas: 'NLPC: Alta absorção de fluidos/hipotermia; Pneumotórax na punção acima da 12ª costela.',
    correcoes: 'Controle térmico agressivo. Aumento súbito da pressão de pico no ventilador indica pneumotórax (checar USG).',
    posOp: 'Infiltração de trajeto da nefrostomia ou bloqueio intercostal.',
    referencias: 'EAU Guidelines on Urolithiasis.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Vasectomia e Correção de Varicocele',
    tempos: '1. Infiltração local/bloqueio de cordão; 2. Excisão/ligadura de vasos ou deferentes.',
    tecnica: 'Local com Sedação Leve (MAC). Microcirurgia de varicocele exige imobilidade (Raquianestesia opcional).',
    problemas: 'Reflexo Vagal intenso (bradicardia/hipotensão) pela tração do cordão espermático.',
    correcoes: 'Pausar estímulo. Atropina (0,5 mg) se necessário.',
    posOp: 'Ambulatorial. Analgesia oral simples, suspensório escrotal.',
    referencias: 'AUA Guideline Vasectomy.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Postectomia (Circuncisão)',
    tempos: '1. Antissepsia; 2. Bloqueio peniano; 3. Excisão do prepúcio.',
    tecnica: 'Pediatria: Geral (ML) + Bloqueio Peniano. Adultos: Local ou Raqui em sela.',
    problemas: 'LAST ou isquemia tecidual grave por uso errôneo de vasoconstritor.',
    correcoes: 'NUNCA usar epinefrina no bloqueio peniano (usar Bupivacaína ou Ropivacaína pura).',
    posOp: 'Alta imediata. Cuidado com retenção urinária por curativo apertado.',
    referencias: 'Coté & Lerman Pediatric Anesthesia.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Cistectomia Radical com Derivação',
    tempos: '1. Exérese de bexiga e linfonodos; 2. Confecção de neobexiga/conduto ileal com alça intestinal.',
    tecnica: 'Geral IOT + GDFT (Terapia Guiada por Metas hemodinâmicas com Flotrac/PiCCO). PAI obrigatória (punho esquerdo). CVC (VJI ou subclávia) para vasopressores. Monitorização de débito cardíaco e variação de pressão de pulso (VPP) contínua. Indução: Etomidato 0,2–0,3 mg/kg ou Propofol 1–1,5 mg/kg + Fentanil + Rocurônio. TIVA ou Balanceada. Sonda gástrica. Aquecimento ativo. TXA 1 g IV na incisão profilático. GDFT: bólus de 200–250 mL cristaloide se VPP > 13% ou IC < 2,5 L/min/m².',
    problemas: 'Perda sanguínea maciça (clampe de pedículo vesical, linfadenectomia extensa); Acidose hiperclorêmica pela alça ileal (HCO3⁻ desperdiçado = acidose metabólica hiperclorêmica sem AG); Hipotermia intraoperatória (cirurgia > 4–6 h, campo aberto); Íleo paralítico prolongado pela alça intestinal; Sepse anastomótica; Trombose venosa profunda (pelve esvaziada — risco altíssimo); Injúria renal aguda por uropatia obstrutiva prévia.',
    correcoes: 'Sangramento: GDFT guiando reposição; Transfusão maciça 1:1:1 se indicada; TXA + agentes hemostáticos tópicos. Acidose hiperclorêmica: usar Ringer Lactato ou Plasmalyte em vez de SF 0,9% durante confecção da derivação; verificar pH e BE no final do caso. Hipotermia: aquecimento ativo (Bair-Hugger, fluidos aquecidos 38–40 °C, cortinas plásticas). Hipotensão: Noradrenalina 0,05–0,2 mcg/kg/min para manter PAM ≥ 65 mmHg e perfusão das anastomoses intestinais (evitar hiper-hidratação que causa edema anastomótico). TVP: Enoxaparina 40 mg SC D0 pós-op, meia elastica, mobilização precoce.',
    posOp: 'ERAS Cistectomia Radical: TAP Block bilateral contínuo com cateter (Ropivacaína 0,2% 6–8 mL/h) substituiu Peridural Torácica como analgesia de escolha (melhor estabilidade hemodinâmica, menor íleo). Analgesia multimodal: Paracetamol 1 g/6 h + AINEs com cautela (monitorar função renal) + Tramadol 50–100 mg/8 h + Morfina PCA de resgate. Dieta oral D1 (imunodulação pré-op com carboidratos). Mobilização D0. Critérios de alta: função da derivação confirmada, trânsito intestinal restabelecido (flatos), dor controlada via oral, sem febre.',
    referencias: 'Cerantola et al., ERAS Society Radical Cystectomy Guidelines 2022. Collins et al., Transversus abdominis plane block for radical cystectomy. Reg Anesth Pain Med 2016. Djaladat et al., Goal-directed fluid therapy in cystectomy. Eur Urol 2014.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Cirurgia de Sling (TVT/TOT)',
    tempos: '1. Litotomia; 2. Incisão vaginal; 3. Passagem de fita retropúbica/transobturatória.',
    tecnica: 'Raquianestesia, MAC ou Geral. Raqui (T10) provê relaxamento de assoalho ideal.',
    problemas: 'Perfuração vesical (TVT) e sangramento de plexos pélvicos.',
    correcoes: 'Cistoscopia intraoperatória mandatória após a passagem da agulha no TVT.',
    posOp: 'Retenção urinária por hipercorreção da fita.',
    referencias: 'AUA/SUFU Guideline Female Stress Urinary Incontinence.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Orquiectomia',
    tempos: 'Radical (câncer): Incisão inguinal, clampeamento alto. Simples: Escrotal.',
    tecnica: 'Raquianestesia, Bloqueio Ilioinguinal ou Geral (se metástase pulmonar).',
    problemas: 'Risco de toxicidade pulmonar (SDRA) se o paciente usou quimioterapia com Bleomicina prévia.',
    correcoes: 'Regra Bleomicina: Manter FiO2 a mais baixa possível (SpO2 > 90–92%) e fluidos restritivos para evitar dano alveolar.',
    posOp: 'TAP Block ilioinguinal para técnica radical.',
    referencias: 'EAU Guidelines on Testicular Cancer.',
  },

  // ── CIRURGIA TORÁCICA ─────────────────────────────────────
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Lobectomia Pulmonar e Segmentectomia',
    tempos: '1. Decúbito lateral; 2. Isolamento pulmonar; 3. Grampeamento vascular/brônquico.',
    tecnica: 'Geral com Ventilação Monopulmonar (TDL — Tubo de Duplo Lúmen): lado esquerdo preferido (35–41 Fr conforme peso). Confirmação por fibroscopia OBRIGATÓRIA após posicionamento lateral. Alternativa: Bloqueador brônquico se via aérea difícil ou brônquio anômalo. Indução: Propofol + Remifentanil + Rocurônio. Manutenção: Sevoflurano ou TIVA. Estratégia ventilatória protetora: Vt 5–6 mL/kg peso predito, PEEP 4–6 cmH2O, FR 12–16 irpm, FiO2 mínima necessária, Ppico < 35 cmH2O. Restrição fluídica rigorosa: < 1,5 mL/kg/h (evitar edema pulmonar pós-lobectomia). PAI obrigatória.',
    problemas: 'Hipoxemia severa durante VMP (shunt intrapulmonar pelo pulmão colapsado, especialmente com PaO2 < 60 mmHg por > 10 min); VILI (volutrauma/barotrauma no pulmão ventilado único); Mau posicionamento do TDL com hipoventilação do pulmão dependente; Atelectasias persistentes no pós-op; Fístula Broncopleural (pós-lobectomia, especialmente se pneumonite ou quimioterapia prévia); Arritmias (manipulação do hilo pulmonar, especialmente FA); Herniação cardíaca pós-pneumonectomia. ',
    correcoes: 'Hipoxemia na VMP: (1) FiO2 100%; (2) CPAP 2–5 cmH2O no pulmão colapsado; (3) PEEP 5–8 cmH2O no ventilado; (4) Ligadura precoce da artéria pulmonar pelo cirurgião; (5) Retorno a ventilação bipulmonar se refratária. VILI: Vt estrito 4–5 mL/kg, aceitar hipercapnia permissiva (PaCO2 até 60 mmHg). Mau posicionamento TDL: auscultação e fibroscopia imediatas ao mudar de posição. FA intraop: Amiodarona 150 mg IV bólus + 1 mg/min infusão. Fístula broncopleural: VMP imediata contralateral para proteger pulmão sadio.',
    posOp: 'PVB (Bloqueio Paravertebral) ou ESP block ipsilateral T4–T5: Ropivacaína 0,25–0,375% 20–25 mL single-shot ou cateter contínuo (padrão-ouro ERAS). Analgesia multimodal: Paracetamol 1 g/6 h + Cetorolaco 15–30 mg/8 h + Dipirona 1 g/8 h. Oxigênio nasal alvo SpO2 ≥ 92–94%. Fisioterapia respiratória D0. Critérios de alta: expansão pulmonar adequada na radiografia, ausência de fuga aérea por > 24 h, drenagem < 200 mL/24 h, dor controlada, SpO2 aceitável em ar ambiente.',
    referencias: 'Batchelor et al., ERAS Lung Surgery 2019. Lohser et al., One-lung ventilation. Curr Opin Anaesthesiol 2015. Blank et al., Optimizing intraoperative management of lung resection. Anesthesiology 2023.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Pneumonectomia',
    tempos: '1. Lateral; 2. VMP; 3. Ligadura de artéria pulmonar principal; 4. Remoção do pulmão.',
    tecnica: 'Geral VMP com TDL contralateral (pulmão remanescente ventilado, pulmão a retirar colapsado). PAI radial bilateral e acesso central (VJI ou subclávia contralateral) obrigatórios. Monitorização de débito cardíaco (PiCCO ou Swan-Ganz) recomendada. Estratégia ventilatória ultra-protetora para pulmão único remanescente: Vt 4–5 mL/kg predito, PEEP 5–8 cmH2O, FR 14–18 irpm. Restrição hídrica drástica: < 1 L intraoperatório total. Preferir vasopressores para manter PAM em vez de expansão volêmica.',
    problemas: 'Edema Pulmonar Pós-Pneumonectomia (ALI/ARDS — mortalidade até 80%); Disfunção Aguda de VD por aumento súbito de RVP no pulmão único; Herniação Cardíaca (emergência cirúrgica por torção do pedículo); Fístula Broncopleural precoce (< 7 dias); Síndrome pós-pneumonectomia (desvio mediastinal tardio); Hipoxemia refratária intraoperatória; Arritmias por manipulação do pericárdio.',
    correcoes: 'Edema Pulmonar Pós-Pneumonectomia: restrição hídrica intraop + pós-op; Furosemida se sobrecarga; VNI ou CPAP no pós-op; suporte com ECMO VV se SDRA refratária. Disfunção VD aguda: iNO (5–20 ppm), Milrinona 0,25–0,75 mcg/kg/min, Noradrenalina para PA sistêmica; evitar fluidos. Herniação Cardíaca: retornar imediatamente ao decúbito lateral operado + reconversão cirúrgica urgente. Fístula Broncopleural: isolamento imediato com TDL para proteger pulmão sadio, posição lateral sobre o lado operado.',
    posOp: 'Posicionamento preferencialmente deitado sobre o lado operado para evitar desvio mediastinal e sobrecarga do pulmão remanescente. UTI mínimo 48–72 h. Restrição hídrica estrita pós-op (< 1 mL/kg/h de cristaloide). Analgesia: PVB ipsilateral ou ESP block contínuo + Paracetamol + AINEs com cautela (monitorar função renal com pulmão único e vasopressores). Fisioterapia respiratória supervisionada. Radiografia de tórax diária para monitorar líquido no saco pneumonectomia (expectativa: aumento progressivo, normal).',
    referencias: 'Slinger et al., Thoracic Anesthesia 3rd Edition. Dulu et al., Prevalence and mortality of acute lung injury after pneumonectomy. Anesthesiology 2006. Decaluwé et al., Major intraoperative complications during video-assisted thoracoscopic anatomical lung resections.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Decorticação Pulmonar e Pleurodese',
    tempos: '1. VATS/Aberta; 2. Remoção de casca fibrótica (empiema) ou talcagem (pleurodese).',
    tecnica: 'Geral com VMP. PAI rotina na decorticação.',
    problemas: 'Sangramento torácico maciço (decorticação); Dor pleurítica excruciante e SIRS (talcagem).',
    correcoes: 'Ácido Tranexâmico 1–2 g profilático. Infiltração pleural direta com Bupivacaína antes do talco.',
    posOp: 'Peridural torácica essencial na decorticação aberta. Proibido AINEs após pleurodese.',
    referencias: 'British Thoracic Society Pleural Disease Guideline.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Mediastinoscopia Cervical',
    tempos: '1. Incisão supraesternal; 2. Dissecção pré-traqueal; 3. Biópsia linfonodal.',
    tecnica: 'Geral com Tubo simples (aramado opcional).',
    problemas: 'Compressão do Tronco Braquiocefálico (isquemia cerebral); Hemorragia de grandes vasos.',
    correcoes: 'MANDATÓRIO oximetria/PAI no braço direito para detectar compressão. Acesso calibroso no braço esquerdo/perna.',
    posOp: 'Observar pneumotórax ou lesão de nervo laríngeo recorrente.',
    referencias: 'Choen\'s Thoracic Anesthesia.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Timectomia e Simpatectomia',
    tempos: '1. VATS/Robótica; 2. Ressecção do timo (Miastenia) ou ablação de gânglio simpático.',
    tecnica: 'Timectomia: Geral, TIVA preferida. Simpatectomia: Geral com Tubo simples e capnotórax seletivo.',
    problemas: 'Miastenia: Sensibilidade extrema a bloqueadores neuromusculares. Simpatectomia: Bradicardia vagal profunda pelo CO2.',
    correcoes: 'Timectomia: Evitar relaxante, ou reverter 100% com Sugammadex (Nível A). Simpatectomia: Pausar CO2 se hipotensão aguda.',
    posOp: 'Critérios estritos de extubação em miastênicos.',
    referencias: 'Gilhus et al., Myasthenia gravis. N Engl J Med.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Correção de Parede Torácica (Pectus Excavatum – Nuss)',
    tempos: '1. VATS direita; 2. Passagem retroesternal de barra curva; 3. Rotação elevando o esterno.',
    tecnica: 'Geral IOT. Ecocardiograma prévio obrigatório.',
    problemas: 'Transfixação letal do coração pela barra; Dor osteoarticular extrema.',
    correcoes: 'Desconectar ventilação durante a passagem do guia para afastar o coração do esterno.',
    posOp: 'Mudança de Paradigma: Crioablação Intercostal substituiu a peridural (Nível 1A) com alta precoce.',
    referencias: 'Graves et al., Cryoanalgesia in Nuss Procedure.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Transplante Pulmonar',
    tempos: '1. Toracotomia/Clamshell; 2. Pneumonectomia; 3. Anastomoses do doador.',
    tecnica: 'Geral Complexa. TDL, PAI, MAC e ETE obrigatórios. ECMO de prontidão.',
    problemas: 'Disfunção Primária do Enxerto (isquemia-reperfusão); Colapso de VD.',
    correcoes: 'Suporte intraoperatório com ECMO VA ou VV reduziu mortalidade (Nível B). Reperfusão lenta com FiO2 baixa (<40%).',
    posOp: 'UTI. Imunossupressão (Metilprednisolona intraop).',
    referencias: 'Machuca et al., ECMO in Lung Transplantation.',
  },

  // ── ORTOPEDIA ─────────────────────────────────────────────
  {
    especialidade: 'Ortopedia',
    nome: 'Artroplastia Total de Quadril e Joelho',
    tempos: '1. Acesso articular; 2. Cortes/Fresagem óssea; 3. Implante com/sem cimento.',
    tecnica: 'Raquianestesia T10 fortemente recomendada (PROSPECT 1A, reduz TVP, perda sanguínea e NVPO): Bupivacaína hiperbárica 0,5% 12,5–15 mg ± Morfina intratecal 0,1–0,15 mg para analgesia prolongada. Geral como alternativa se contraindicação. Torniquete: insuflar 250 mmHg (quadril) ou 300 mmHg (joelho), tempo < 90 min contínuos. Cimento: alertar cirurgião para monitorização cardiovascular estrita 30–60 s após cimentação. TXA: 15–20 mg/kg IV na indução + 15–20 mg/kg no fechamento (ou dose única 2–3 g IV); tópico intraarticular 1,5–3 g opcional.',
    problemas: 'Síndrome de Implantação de Cimento (BCIS) — graus I (hipotensão), II (hipotensão grave + hipoxemia), III (colapso cardiovascular); Dor do torniquete (breakthrough intraop após 45–60 min mesmo sob raqui); Embolia gordurosa ou medular sistêmica; TVP/TEP perioperatório; Lesão de nervo femoral ou ciático (ATQ via posterior); Luxação intraoperatória ou instabilidade protética; Rigidez de membros pelo espasmo muscular.',
    correcoes: 'BCIS Grau I: O2 100%, expansão cuidadosa com 250–500 mL cristaloide. Grau II: Efedrina 5–10 mg ou Fenilefrina 100–200 mcg, O2 100%. Grau III: Adrenalina 10–100 mcg IV, RCP se necessário; alertar cirurgião 30 s antes da cimentação para minimizar pressão de injeção (técnica retrógrada). Dor de torniquete: Propofol 0,5–1 mg/kg ou Remifentanil 0,5–1 mcg/kg, deflação imediata se insuportável. TVP/TEP: Enoxaparina 40 mg SC a partir de D0 pós-op (ERAS).',
    posOp: 'ATJ: Adductor Canal Block (ACB) ecoguiado — Ropivacaína 0,25% 20 mL, single-shot ou cateter; preserva força do quadríceps para fisioterapia precoce. Suplementar com iPACK (Interspace between Popliteal Artery and Capsule of Knee) para dor posterior. ATQ: PENG Block (Pericapsular Nerve Group) ecoguiado — Ropivacaína 0,25% 20 mL para dor anterior de quadril. Multimodal: Paracetamol 1 g/6 h + Celecoxibe 200–400 mg/dia + Dipirona 1 g/8 h + Morfina oral (S-PCA). Crioterapia intermitente. Fisioterapia D0 (sentar), D1 (deambular com andador). Alta D2–D3.',
    referencias: 'Memtsoudis et al., ERAS Total Joint Arthroplasty 2019. Macfarlane et al., Adductor canal block in knee replacement: meta-analysis. Br J Anaesth 2019. Parvizi et al., Bone cement implantation syndrome. JBJS 2012.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Artroscopia de Joelho e Reconstrução de LCA',
    tempos: '1. Garrote; 2. Retirada de enxerto tendíneo; 3. Fixação via túneis ósseos.',
    tecnica: 'Raquianestesia de curta duração: Cloroprocaína 2% 40–50 mg (duração 45–60 min, alta ambulatorial precoce) ou Bupivacaína hiperbárica 0,5% baixas doses (7,5–10 mg) + Fentanil 20 mcg intratecal para LCA. Geral com ML: Propofol + Remifentanil, alternativa eficaz para artroscopia curta. Torniquete: insuflar 300 mmHg (150 mmHg + PA sistólica), máximo 90 min contínuos. LCA: enxerto de osso-tendão-osso (BTB) vs. tendões isquiotibiais — dor diferente (BTB = dor anterior de joelho, isquiotibiais = dor medial de coxa).',
    problemas: 'Dor Inibitória Reflexa do Quadríceps (especialmente enxerto BTB — dor patelar residual em 15–30%); Dor de Torniquete (breakthrough após 45–60 min de isquemia); Hemartrose pós-op com bloqueio fechado em sangramento articular; Neuropraxia do Nervo Safeno (dissecção enxerto isquiotibial); Síndrome Compartimental de compartimento anterior por sangramento pós-desinflação do torniquete; Trombose venosa profunda pelo torniquete prolongado; Mal funcionamento do enxerto.',
    correcoes: 'Dor BTB: Bloqueio Femoral 3-em-1 ecoguiado ou ACB (Adductor Canal Block) Ropivacaína 0,25% 20 mL + infiltração local por cirurgião. Dor Medial (isquiotibial): Bloqueio do nervo Safeno + infiltração local. iPACK (Interspace between Popliteal Artery and Capsule of Knee): Ropivacaína 0,25% 20 mL para dor posterior sem bloquear motricidade. Torniquete: Propofol 0,5–1 mg/kg bólus ou aprofundar sedação; deflação precoce se > 90 min. Hemartrose: aspiração intraoperatória sob visão artroscópica + dreno se necessário.',
    posOp: 'Day-clinic (alta 2–4 h pós-op se anestesia local/raqui curta). Crioterapia agressiva pós-op intermitente: 20 min/hora por 48 h (reduz 30–40% do consumo de analgésicos). Analgesia multimodal: Paracetamol 1 g/6 h + Celecoxibe 200 mg 12/12 h + Dipirona 1 g/8 h + Codeína 30 mg 6/6 h pós-op imediato (adultos). Elevação do membro. Muletas com carga parcial D0. Fisioterapia: mobilização articular D1, exercícios isométricos de quad D0.',
    referencias: 'Lavoie-Gagne et al., Pain Control in ACL Reconstruction. Arthroscopy 2022. Abdallah et al., Adductor canal block for knee surgery. Anesthesiology 2016. Gaffney et al., Tourniquet use in knee surgery. Knee Surg Sports Traumatol Arthrosc 2018.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Reparo de Manguito Rotador / Artroscopia de Ombro',
    tempos: '1. Cadeira de Praia (Beach Chair) ou Lateral; 2. Portais; 3. Sutura com âncoras.',
    tecnica: 'Geral IOT combinada com Bloqueio Interescalênico do Plexo Braquial (C5-C6 ecoguiado): Ropivacaína 0,5% 15–20 mL proporciona analgesia de 12–18 h e reduz 70% dos opioides intraop. Posição Beach Chair (sentada 30–40°): calcular PAM no nível do meato auditivo externo (cada 10 cm de diferença de altura = 7,5 mmHg). Monitorização: PAI no braço contralateral (NUNCA ipsilateral ao bloqueio). Posição Lateral Decúbito: alternativa; tração axial de 5–7 kg. Manter normocapnia — hipocapnia agrava isquemia cerebral.',
    problemas: 'Isquemia Cerebral (posição Beach Chair: PAM calculada na cabeça pode ser 20–30 mmHg menor que a medida no braço — subdiagnóstico); Reflexo de Bezold-Jarisch (bradicardia + hipotensão profunda súbita — especialmente em pacientes jovens hipovolêmicos); Paralisia do Nervo Frênico pelo Bloqueio Interescalênico (100% de incidência — reduz CVF 25%); Pneumotórax pelo Interescalênico (rare < 0,1%); Bloqueio Bilateral inadvertido do Frênico (insuficiência respiratória); Síndrome de Horner; LAST.',
    correcoes: 'PAM Beach Chair: alvo PAM ≥ 65–70 mmHg MEDIDA no nível da cabeça (subtrair 0,77 mmHg por cm de diferença entre braço e cabeça). Usar NIRS cerebral bilateral ou Doppler cerebral médio. Bezold-Jarisch: Efedrina 10 mg IV ou Atropina 0,5 mg + posicionar Trendelenburg rápido; pré-carga com 500 mL cristaloide preventiva em pacientes jovens. DPOC Grave: substituir interescalênico por Bloqueio Suprascapular ecoguiado (preserva frênico) + Bloqueio Axilar de Nervo Axilar (cobertura mais limitada mas segura). LAST: Intralipid 20% 1,5 mL/kg bólus.',
    posOp: 'Bloqueio Interescalênico single-shot (padrão-ouro — Ropivacaína 0,5%): 12–18 h de analgesia. Alternativa para alta ambulatorial: cateter contínuo perineural Interescalênico com elastômero Ropivacaína 0,2% a 5 mL/h. DPOC grave/pulmão único: Suprascapular + axilar do nervo axilar (sem impacto respiratório). Multimodal: Paracetamol 1 g/6 h + Celecoxibe 200 mg 12/12 h + Gabapentina 300 mg 12/12 h por 5 dias. Tipoia por 4–6 semanas. Fisioterapia pendular D1.',
    referencias: 'Rains et al., Position-related complications in shoulder surgery. Arthroscopy 2011. Lee et al., Interscalene brachial plexus block for shoulder surgery. Reg Anesth Pain Med 2018. Bhatt et al., Cerebral desaturation in beach chair position. Anesth Analg 2020.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Liberação do Túnel do Carpo',
    tempos: '1. Incisão tenar; 2. Secção do ligamento carpal.',
    tecnica: 'Técnica WALANT (Lidocaína+Epinefrina acordado) sem garrote. Ou Bloqueio de Bier.',
    problemas: 'Mito sobre necrose de extremidades com adrenalina foi refutado.',
    correcoes: 'Se isquemia digital persistir, usar Fentolamina local.',
    posOp: 'Analgesia simples oral.',
    referencias: 'Lalonde et al., Wide awake hand surgery.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Artrodese de Coluna Lombar / Discectomia',
    tempos: '1. Decúbito prono; 2. Parafusos pediculares; 3. Laminectomia/Cages.',
    tecnica: 'Geral TIVA (Propofol + Remifentanil) se uso de PEM (Potencial Evocado Motor) — halogenados e N2O suprimem PEM. Relaxamento neuromuscular PROIBIDO após indução (monitorização contínua com TOF no addutor do polegar). Alternativa MEPs tolerada com Sevoflurano < 0,5 MAC + Remifentanil. Posicionamento prono: calcanhares protegidos, braços em extensão < 90°, olhos protegidos com fita, ventre livre (Pelikan frame ou Wilson). PAI obrigatória. CVC ou acesso central recomendado. Monitorização SSEP + PEM + EMG radicular. Temperatura e débito urinário contínuos.',
    problemas: 'POVL — Neuropatia Óptica Isquêmica (NOI) perioperatória: fatores de risco — anemia, hipotensão, posição prono > 6 h, volume maciço de cristaloide, compressão ocular; Sangramento maciço do plexo venoso de Batson (compressão abdominal → desvio sangue para epidural); Lesão de plexo braquial por posicionamento incorreto dos ombros; Perda de sinal de PEM (isquemia medular); Síndrome Compartimental orbitária por edema; Rabdomiólise e síndrome compartimental muscular (prono > 6 h); Pneumonia por posição (aspiração ao prono).',
    correcoes: 'POVL: Verificar posição da cabeça neutra + olhos livres a cada 30 min; Manter PAM ≥ 65–70 mmHg, Hgb ≥ 8 g/dL, sem compressão ocular; Se suspeita pós-op → oftalmologista emergencial. Batson: abdome pendular/livre na mesa, confirmar manualmente no início. Anemia: transfundir se Hgb < 8 g/dL em cirurgia > 3 h. Perda de PEM: comunicar cirurgião imediatamente, aumentar PAM para > 80 mmHg, excluir lesão mecânica; se persistir > 10 min → avaliar wake-up test. Queda de Remifentanil: dose de Ketamina 0,1–0,3 mg/kg IV no final para prevenir hiperalgesia.',
    posOp: 'Extubação sem tosse se reparo de dura-máter intraop (usar Dexmedetomidina 0,5–1 mcg/kg + Lidocaína 1,5 mg/kg IV antes de aspirar). Ketamina S+ 0,1–0,3 mg/kg antes do fim para prevenir hiperalgesia do Remifentanil. Analgesia multimodal: Paracetamol 1 g/6 h + Dipirona 1 g/8 h + Gabapentina 300–600 mg/12 h (modulação central) + Morfina PCA para breakthrough. Fisioterapia motora imediata nas primeiras horas para avaliação neurológica de MMII. Avaliar dor neuropática radicular pós-descompressão (Duloxetina ou Pregabalina).',
    referencias: 'ASA Task Force on Perioperative Visual Loss 2019. Kamel et al., Anesthetic considerations for spinal fusion. AINS 2016. Boonstra et al., Total intravenous anesthesia vs. inhalational anesthesia in spine surgery for neuromonitoring. J Neurosurg Spine 2018.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Osteossíntese e Fixação Externa (Trauma)',
    tempos: '1. Fresagem de canal (reaming); 2. Inserção de hastes/placas ou fixadores em damage control.',
    tecnica: 'Membros inferiores: Raquianestesia (Bupivacaína hiperbárica 0,5% 12,5–15 mg) para fixação eletiva. Membros superiores: Bloqueio Supraclavicular ou Interescalênico ecoguiado (Ropivacaína 0,5% 20 mL). Trauma grave/instável: Geral RSI (Cetamina 1–2 mg/kg + Succinilcolina 1,5 mg/kg ou Rocurônio 1,2 mg/kg). Damage Control Orthopedics (DCO) em politraumatizado: fixador externo sob anestesia mínima, definitivação eletiva após estabilização (72–96 h). Aquecimento ativo obrigatório (esteira aquecida, Bair-Hugger, fluidos aquecidos).',
    problemas: 'Embolia Gordurosa Pulmonar (queda súbita EtCO2 + PaO2 na inserção de haste intramedular — especialmente fêmur); Tríade Letal do Trauma (Hipotermia + Coagulopatia + Acidose); Síndrome Compartimental Aguda (oculta por bloqueios de longa duração); Síndrome de Embolia Gordurosa sistêmica (petéquias, hipoxemia, disfunção neurológica 24–72 h pós-trauma); Hemorragia pós-fresagem de canal; Embolia Pulmonar por TVT de longa data no trauma pélvico.',
    correcoes: 'Embolia Gordurosa: Suporte O2/ventilatório 100%; aumentar PEEP; tratar hipotensão com Noradrenalina; comunicar cirurgião (pausar fresagem); ECMO se refratário. Tríade Letal: Protocolo de Transfusão Maciça 1:1:1 (CH:PFC:Plaquetas) + Ácido Tranexâmico 1 g IV nos primeiros 3 h do trauma (CRASH-2, 1A) + aquecimento ativo + Fibrinogênio se < 1,5 g/L. Síndrome Compartimental: preferir bloqueios de curta duração (Ropivacaína 0,2%) em fraturas fechadas; se suspeita, fasciotomia cirúrgica imediata. Coagulopatia: guiar por ROTEM/TEG.',
    posOp: 'Bloqueios regionais: considerar risco de mascarar Síndrome Compartimental aguda em fraturas fechadas de MMII (preferir concentrações menores de AL). Analgesia multimodal: Paracetamol 1 g/6 h + AINEs com cautela (controvertido na consolidação óssea) + Tramadol 50–100 mg/8 h + Ketamina subdissociativa 0,1–0,3 mg/kg/h por 24–48 h (trauma grave). Profilaxia TVP: Enoxaparina 40 mg SC a partir de 12–24 h pós-op estabilizado. Reabilitação precoce supervisionada.',
    referencias: 'ATLS Guidelines 10th Edition. CRASH-2 Collaborators, TXA for trauma. Lancet 2010. Gosselin et al., Damage control orthopedics. JBJS 2004. Weinlein et al., Acute compartment syndrome: diagnosis and management. JAAOS 2015.',
  },

  // ── OTORRINOLARINGOLOGIA ──────────────────────────────────
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Amigdalectomia, Adenoidectomia e Miringotomia',
    tempos: '1. Abridor de boca; 2. Eletrocautério/frio. Miringotomia: incisão e tubo de ventilação.',
    tecnica: 'Amigdalectomia/Adenoidectomia: Geral IOT com Tubo RAE preformado (tamanho conforme idade). Indução: Sevoflurano inalatório (crianças) ou TIVA (adultos, menor NVPO). Manutenção Sevoflurano ou TIVA. Abridor de boca (Boyle-Davis): risco de dobrar tubo ou extubação acidental — verificar posição após instalação. Miringotomia: Inalatória pura sob máscara facial sem IOT (curta duração < 5 min). Dexametasona 0,15 mg/kg IV (máx 8 mg) na indução: reduz dor e edema. Infiltração tonsilar com Lidocaína + Adrenalina 1:200.000 pelo cirurgião: diminui sangramento e analgesia intraop.',
    problemas: 'Sangramento Pós-Tonsilectomia (0,5–2% das cirurgias, perigoso pois mascarado por deglutição — diagnóstico tardio); NVPO altíssima em crianças (incidência sem profilaxia > 70%); Laringoespasmo na extubação (secreções e estimulação); Edema de via aérea pós-op (crianças com IVAS recente); Síndrome de Apneia Obstrutiva do Sono (obstrução pós-extubação na amigdalite obstrutiva); Hipotermia em procedimentos pediátricos curtos; Toxicidade de Codeína em metabolizadores ultra-rápidos (risco de morte).',
    correcoes: 'Reabordagem por Sangramento (emergência): paciente vomitou sangue → estômago cheio → RSI obrigatório (Succinilcolina 2 mg/kg em < 10 kg; Rocurônio 1,2 mg/kg + Sugammadex disponível). Aspirar estômago antes de extubar. NVPO: profilaxia dupla obrigatória (Dexametasona 0,15 mg/kg + Ondansetrona 0,1 mg/kg IV). TIVA em adultos (reduz 50% NVPO). Laringoespasmo: CPAP com máscara, Propofol 0,5 mg/kg IV, Succinilcolina 0,5–1 mg/kg se refratário. Apneia pós-op em criança com SAOS grave: monitorização SpO2 mínimo 2 h, UTI pediátrica se apneia central prévia.',
    posOp: 'ALERTA FDA: PROIBIDO Codeína e Tramadol em < 12 anos (risco de morte por sobredose em metabolizadores ultra-rápidos do CYP2D6). Analgesia pediátrica segura: Ibuprofeno 10 mg/kg/dose 6/6 h (seguro em metanálise — reduz dor sem aumentar sangramento) + Paracetamol 15 mg/kg/dose 6/6 h regular. Adultos: Paracetamol + AINEs + Tramadol cuidadoso + Dipirona. Dieta pastosa fria por 7 dias. Vigilância de sangramento tardio pico D5–D10 (escaras). Alta após 2 h de observação se estável; internação se SAOS grave, sangramento ou dor refratária.',
    referencias: 'FDA Drug Safety Communication regarding Codeine in Pediatrics 2013. Merry et al., Pain management after tonsillectomy. Cochrane Review. Gallagher et al., NVPO prophylaxis in adenotonsillectomy. Paediatr Anaesth 2019.',
  },
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Septoplastia, Turbinectomia e FESS (Sinusectomia)',
    tempos: '1. Infiltração vasoconstritora; 2. Endoscopia nasossinusal/ressecção.',
    tecnica: 'Geral TIVA (Padrão 1A para FESS) para melhorar campo visual e reduzir sangramento.',
    problemas: 'Toxicidade sistêmica por adrenalina local (taquicardia/hipertensão); Lesão de base de crânio/órbita.',
    correcoes: 'Dose de adrenalina máx 5–7 mcg/kg. Controle de PA/FC estrito (Hipotensão controlada com Beta-bloqueador).',
    posOp: 'Despertar suave (Dexmedetomidina ou Deep Extubation) para evitar tosse e epistaxe no extubar.',
    referencias: 'Wormald et al., TIVA vs Inhalational in FESS.',
  },
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Timpanoplastia e Mastoidectomia',
    tempos: '1. Fresagem óssea; 2. Enxerto timpânico.',
    tecnica: 'Geral Balanceada/TIVA. Relaxante neuromuscular restrito se uso de monitorização do nervo facial.',
    problemas: 'Expulsão do enxerto timpânico por expansão de gás.',
    correcoes: 'REGRA: Proibido o uso de Óxido Nitroso (N2O) na fixação do enxerto (expande na câmara fechada).',
    posOp: 'Terapia NVPO agressiva. Evitar vômito pós-operatório.',
    referencias: 'Eisele et al., Nerve monitoring.',
  },
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Microcirurgia de Laringe',
    tempos: '1. Laringoscopia de suspensão; 2. LASER de corda vocal.',
    tecnica: 'Geral com Tubo seguro para Laser (MLT) ou Jet Ventilation. Via aérea compartilhada.',
    problemas: 'Incêndio na Via Aérea (Airway Fire); Reflexo autônomo severo à suspensão.',
    correcoes: 'Algoritmo Incêndio (ASA): FiO2 < 30%, usar ar comprimido. Sem N2O. Balonete insuflado com soro + azul de metileno.',
    posOp: 'Dexametasona obrigatória contra edema de glote. Adrenalina racêmica inalatória.',
    referencias: 'ASA Practice Advisory on Operating Room Fires.',
  },
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Rinoplastia e Otoplastia',
    tempos: '1. Infiltração local extensa; 2. Fraturas nasais ou ressecção de cartilagem auricular.',
    tecnica: 'Rino: Geral ou Sedação Profunda. Otoplastia: Local + MAC.',
    problemas: 'Sangramento/Equimose; Náuseas severas por deglutição de sangue.',
    correcoes: 'Ácido Tranexâmico IV (10–15 mg/kg) pré-incisão. Controle de PAM com Dexmedetomidina.',
    posOp: 'Deep Extubation é recomendada se via aérea favorável (evitar tosse). Risco hematoma retroauricular.',
    referencias: 'Daniel, Rhinoplasty Anesthetic Management.',
  },

  // ── NEUROCIRURGIA ─────────────────────────────────────────
  {
    especialidade: 'Neurocirurgia',
    nome: 'Craniotomia (Tumor, Aneurisma, Epilepsia)',
    tempos: '1. Pinos Mayfield; 2. Craniotomia; 3. Exérese tumoral ou Mapeamento por ECoG (Epilepsia).',
    tecnica: 'Geral TIVA (Propofol 4–6 mg/kg/h + Remifentanil 0,1–0,3 mcg/kg/min) é padrão neuroanestésico — menor impacto em PIC e preserva autorregulação cerebral. Halogenados: aceitáveis em < 1 MAC se PIC normal. Indução: Propofol 1–2 mg/kg + Fentanil 2–5 mcg/kg + Lidocaína 1,5 mg/kg (atenua resposta pressórica à laringoscopia) + Rocurônio 0,6 mg/kg. Fixação nos pinos Mayfield: bólus de Remifentanil 1 mcg/kg ou infiltração local antes. PAI obrigatória antes da indução. Na Epilepsia/Awake: protocolo Dexmedetomidina + Remifentanil na fase de mapeamento ECoG, paralisar sedativos durante a estimulação cortical. Posição semi-sentada (aneurisma): risco de embolia aérea venosa — capnotórax de Doppler pré-cordial ou ETE.',
    problemas: 'Hipertensão Intracraniana ("Tight Brain" — cérebro tenso na abertura da dura); Ruptura de Aneurisma intraoperatória (sangramento catastrófico); Crise Convulsiva intraoperatória (tumor/epilepsia); Embolia Aérea Venosa (posição sentada); Edema Cerebral maligno pós-ressecção; Hematoma intracerebral tardio; Diabetes Insipidus central (ressecção hipofisária ou diencéfalo); SIADH pós-craniotomia; Isquemia por vasoespasmo (aneurisma roto); Lesão de nervos cranianos.',
    correcoes: 'Tight Brain: (1) verificar posição da cabeça (sem compressão jugular); (2) Manitol 20% 0,5–1 g/kg IV em 15–20 min OU Salina 3% 150–250 mL; (3) hiperventilação temporária PaCO2 30–35 mmHg; (4) aprofundar anestesia; (5) Dexametasona 10 mg IV se tumor/edema; (6) drenagem de LCR lombar. Ruptura de aneurisma: hipotensão controlada temporária (Labetalol ou Nitroprussiato), oclusão temporária do clipe pelo cirurgião. Crise no ECoG: irrigar córtex com soro fisiológico gelado 4 °C; Propofol 0,5 mg/kg bólus; Diazepam 2 mg IV se refratário. Embolia Aérea: Durant, aspirar CVC, Trendelenburg, tratar hipotensão.',
    posOp: 'UTI com monitorização contínua de PIC se necessário. Despertar neurocirúrgico precoce e SUAVE: Lidocaína 1,5 mg/kg IV + Dexmedetomidina 0,5 mcg/kg 10 min antes de aspirar; extubar em plano leve sem tosse (essencial para exame neurológico imediato e para aneurismas). Analgesia multimodal: Paracetamol 1 g/6 h + Dipirona 1 g/8 h (AINEs contraindicados pelo risco de sangramento); Tramadol com cautela (abaixa limiar convulsivo); Scalp block pré-incisão com Ropivacaína 0,375% reduz consumo de opioides intraop. Profilaxia anticonvulsivante (tumor/epilepsia): Levetiracetam 500–1000 mg/12 h.',
    referencias: 'Sharma et al., SNACC Neurocritical Care Guidelines. Flexman et al., Clinical Neuroanesthesia 2019. Steiner et al., Cerebral Blood Flow and Autoregulation. Smith et al., Anesthetic management of intracranial aneurysm surgery. Anesthesiology 2021.',
  },
  {
    especialidade: 'Neurocirurgia',
    nome: 'Embolização Endovascular de Aneurisma',
    tempos: '1. Acesso femoral/radial; 2. Cateterismo cerebral fluoroscópico; 3. Coils/Stents.',
    tecnica: 'Geral IOT obrigatória (imobilidade rigorosa para subtração digital).',
    problemas: 'Ruptura de aneurisma intra-op pelo cateter; Tromboembolismo; Ambiente hostil (radiologia).',
    correcoes: 'Ruptura: Hipotensão aguda + reversão com Protamina (1 mg/100 UI Heparina). Trombose: Tirofiban local.',
    posOp: 'Observar sítio de punção (hematoma retroperitoneal).',
    referencias: 'Raper et al., SNACC Endovascular Guidelines.',
  },
  {
    especialidade: 'Neurocirurgia',
    nome: 'Estimulação Cerebral Profunda (DBS)',
    tempos: '1. Halo estereotáxico; 2. Perfuração; 3. Microeletrodo no núcleo subtalâmico.',
    tecnica: 'Awake Craniotomy. Dexmedetomidina é a droga de escolha.',
    problemas: 'Propofol e GABAérgicos inibem leitura do núcleo alvo. Ansiedade extrema com crânio fixo.',
    correcoes: 'Manter PAS < 140 mmHg para evitar hematoma intracraniano no trajeto da agulha. Comunicação contínua.',
    posOp: 'Cefaleia pós-op. Internalização da bateria segue sob Geral.',
    referencias: 'Venkatraghavan et al., Anesthesia for DBS.',
  },
  {
    especialidade: 'Neurocirurgia',
    nome: 'Derivação Ventriculoperitoneal e ETV',
    tempos: 'DVP: Cateter crânio-abdome. ETV (Endoscópica): Perfuração do 3º ventrículo.',
    tecnica: 'Geral IOT. Evitar hipercapnia (risco de herniação por hidrocefalia prévia).',
    problemas: 'ETV: Reflexo de Cushing (bradicardia extrema/assistolia) ao perfurar o diencéfalo. DVP: Dor aguda do tunelizador.',
    correcoes: 'ETV: Pausar irrigação endoscópica imediatamente (reflexo autônomo passa rápido). Usar fluidos a 37 °C.',
    posOp: 'Diabetes insipidus transitório pós-ETV.',
    referencias: 'Schroeder et al., Endoscopic neurosurgery.',
  },
  {
    especialidade: 'Neurocirurgia',
    nome: 'Craniectomia Descompressiva (Trauma)',
    tempos: '1. Remoção de grande retalho ósseo; 2. Duroplastia de expansão.',
    tecnica: 'Emergência absoluta (TCE grave GCS ≤ 8, AVC hemorrágico maligno, infarto maligno de ACM). TIVA: Propofol + Remifentanil se hemodinamicamente estável. Ketamina 1–2 mg/kg (segura no TCE quando combinada com benzodiazepínico; reverte mito de aumento de PIC — evidência atual 1B). RSI obrigatório: Succinilcolina 1,5 mg/kg ou Rocurônio 1,2 mg/kg (ter Sugammadex disponível). Evitar Etomidato em TCE pediátrico (supressão adrenal). PAI antes da indução se tempo permitir; se não: imediatamente após. Hiperventilação temporária (PaCO2 30–35 mmHg) apenas na herniação iminente — NÃO como profilaxia rotineira.',
    problemas: 'Choque hemorrágico associado (politrauma — TCE + hemorragia abdominal/pélvica); Tríade de Cushing (bradicardia + hipertensão + respiração irregular = herniação ativa); Coagulopatia associada ao TCE (liberação de fator tecidual cerebral); Convulsões perioperatórias; Diabetes Insipidus e distúrbios de sódio; Hipertermia neurogênica pós-craniectomia; Rabdomiólise e falência renal aguda; Pneumonia de aspiração (TCE com vômito).',
    correcoes: 'Metas Hemodinâmicas (Brain Trauma Foundation 2022): PPC = PAM – PIC; alvo PPC 60–70 mmHg. Noradrenalina para manter PAM ≥ 70–80 mmHg. Monitorização de PIC (sensor intraparenquimatoso ou DVE). Salina Hipertônica 3%: 250–500 mL se PIC > 20 mmHg refratária, ou 23,4% 30 mL se herniação iminente. Manitol 20% 0,5–1 g/kg: alternativa, evitar se osmolaridade > 320 mOsm/L. Temperatura: alvo normotermia (hipotermia terapêutica NÃO recomendada rotineiramente). Coagulopatia: TXA 1 g IV se < 3 h do trauma (CRASH-3). Convulsões: Fenitoína/Levetiracetam profilático por 7 dias.',
    posOp: 'UTI com cabeceira 30° (posição neutra da cabeça, sem compressão jugular). Monitorização de PIC contínua com DVE (drenagem de LCR se PIC > 20 mmHg). Pressão de perfusão cerebral alvo 60–70 mmHg. Controle glicêmico: 140–180 mg/dL. Normotermia estrita. Eunatremia ou hipernatremia leve (140–155 mEq/L) para prevenir edema cerebral. Profilaxia de infecção de ferida e meningite. Sedoanalgesia: Propofol + Remifentanil ou Midazolam + Morfina com avaliação neurológica 3/3 h (interrupção diária). Cranioplastia programada 3–6 meses após craniectomia.',
    referencias: 'Carney et al., Brain Trauma Foundation Guidelines 4th Edition 2016 (update 2022). CRASH-3 Trial Collaborators, TXA in traumatic brain injury. Lancet 2019. Hawryluk et al., Current recommendations for CSF drainage in TBI. Neurocrit Care 2022.',
  },

  // ── GINECOLOGIA ───────────────────────────────────────────
  {
    especialidade: 'Ginecologia',
    nome: 'Histerectomia, Miomectomia e Ressecção de Endometriose',
    tempos: '1. Laparoscópica/Robótica/Aberta; 2. Ressecção com manipulação extensa pélvica.',
    tecnica: 'Geral IOT (TIVA com Propofol + Remifentanil preferida) para laparoscopia com Trendelenburg > 20° e pneumoperitônio prolongado. Raquianestesia T10 (Bupivacaína hiperbárica 12,5 mg + Morfina 0,1 mg intratecal) para histerectomia vaginal ou casos < 2 h. Bloqueio neuromuscular profundo (PTC 0–1) recomendado durante a laparoscopia. Monitorização: acesso periférico calibroso duplo (miomas hipervasculares), hemograma pré-op atualizado; PAI se alto risco de sangramento. Endometriose: TIVA com Ketamina 0,1–0,3 mg/kg/h infusão + Dexmedetomidina 0,3–0,5 mcg/kg/h para modulação de dor crônica centralizada.',
    problemas: 'Sangramento Maciço por miomas hipervasculares (necessidade de transfusão intraop); Crise Hipertensiva por Vasopressina intrauterina (dose > 6 UI ou injeção intravascular acidental); Bradicardia ou parada cardíaca por Vasopressina sistêmica; Lesão de ureter (15% das histerectomias ampliadas); Lesão de vasos ilíacos ou bexiga; Dor crônica pós-operatória centralizada (endometriose — sensibilização central); Deiscência de cúpula vaginal; NVPO elevada (laparoscopia pélvica + opioides).',
    correcoes: 'Sangramento: TXA 1 g IV na incisão + 1 g na 3ª hora; Misoprostol intrauterino ou Ocitocina 10 UI em bólus lento para reduzir perda em miomectomia. Vasopressina: dose máxima 4–6 UI por infiltração; avisar anestesista antes de injetar; Nitroglicerina 100–200 mcg IV ou Fentolamina 1 mg IV para crise hipertensiva. Bradicardia por Vasopressina: Atropina 0,5 mg IV. Lesão de ureter: cistoscopia intraoperatória com índigo-carmim IV é custo-efetiva em histerectomias radicais. NVPO: profilaxia tripla (Dexametasona 4–8 mg + Ondansetrona 4 mg + Droperidol 0,625 mg) e TIVA.',
    posOp: 'ERAS Ginecológico: TAP block bilateral ecoguiado (Ropivacaína 0,25% 20 mL/lado) ou QLB (histerectomia aberta) substituiu peridural torácica (melhor estabilidade hemodinâmica). Alta acelerada D1–D2 (laparoscópica) ou D2–D3 (aberta). Analgesia multimodal: Paracetamol 1 g/6 h + Celecoxibe 200 mg 12/12 h + Dipirona 1 g/8 h ± Morfina PCA de resgate. Endometriose: continuar Gabapentina 300 mg 8/8 h pós-op por 7–14 dias + seguimento com dor. Mobilização precoce D0 (sentar), D1 (deambular). Sonda urinária retirada < 24 h.',
    referencias: 'Nelson et al., ERAS Gynecologic/Oncology Society Guidelines 2019. Rosero et al., Spinal analgesia for hysterectomy. Anesth Analg 2015. Gibbons et al., Vasopressin-related complications in gynecologic laparoscopy. JMIG 2021.',
  },
  {
    especialidade: 'Ginecologia',
    nome: 'Cirurgias Anexiais, Laqueadura e Bartholinectomia',
    tempos: '1. Ressecção ovariana/tubária laparoscópica ou Exérese de cisto vulvar.',
    tecnica: 'Geral com Máscara Laríngea (procedimentos < 1 h) ou Raquianestesia T4 (Laqueadura pós-parto).',
    problemas: 'Dor referida no ombro (escapulalgia por CO2 frênico). Abscesso de Bartholin agudo impede ação de anestesia local (pH baixo).',
    correcoes: 'Esvaziar abdome de CO2 sob manobra de recrutamento inspiratório ativo.',
    posOp: 'Alta no dia (Day-clinic). Analgesia multimodal oral.',
    referencias: 'SAMBA Guidelines.',
  },
  {
    especialidade: 'Ginecologia',
    nome: 'Histeroscopia Cirúrgica e Conização (CAF)',
    tempos: '1. Dilatação cervical; 2. Ressecção uterina com fluido sob pressão ou alça térmica no colo.',
    tecnica: 'Histeroscopia: Sedação (MAC) com Propofol TCI + Remifentanil 0,05–0,1 mcg/kg/min ou Raquianestesia curta (Cloroprocaína 40–50 mg ou Bupivacaína hiperbárica 0,5% 7,5 mg). Bloqueio Paracervical pelo cirurgião (Lidocaína 1% 10 mL bilateral nas 4 e 8 horas) complementa sedação e reduz dor de dilatação. CAF (Conização com Alça de Fritz): Geral ou Sedação Profunda + Bloqueio Paracervical. Monitorização do déficit de irrigação: anestesista deve registrar volume instilado vs. coletado a cada 15 min — alertar se déficit > 750 mL (Bipolar) ou > 500 mL (Glicina/Manitol).',
    problemas: 'Intoxicação Hídrica/Síndrome de Distensão Uterina: Bipolar (SF 0,9%) — déficit > 2.500 mL → risco de EAP; Monopolar (Glicina ou Manitol 1,5%) — déficit > 1.000 mL → hiponatremia grave + hiperamonemia (Glicina); Reflexo Vasovagal intenso (bradicardia + hipotensão) pela dilatação cervical; Dor em queimação no CAF; Perfuração uterina (emergência cirúrgica); Embolia gasosa pelo gás de extração do vapor de RF.',
    correcoes: 'Síndrome de Distensão com Bipolar: se déficit 1.500 mL → interromper procedimento; se 2.000 mL → encerrar e medir Na⁺ sérico imediatamente. Tratar hiponatremia sintomática (< 130 mEq/L): NaCl 3% 100 mL bólus lento; Furosemida 20 mg IV. Síndrome com Glicina: mesmo limite de 1.000 mL; tratar hiponatremia + hiperamonemia (suporte intensivo). Vasovagal: Atropina 0,5 mg IV, elevar MMII. Perfuração uterina: interromper histeroscopia, avaliação laparoscópica urgente se suspeita de lesão de víscera.',
    posOp: 'AINEs para cólicas uterinas: Ibuprofeno 400–600 mg 8/8 h ou Naproxeno 500 mg 12/12 h, iniciar 1 h antes do procedimento se eletivo. Paracetamol 1 g/6 h regular. Observação mínima 1 h após MAC para recuperação do estado de consciência. Sódio sérico se déficit > 500 mL. Alta ambulatorial com acompanhante após recuperação completa. Orientar sobre cólicas e sangramento leve esperado por 7–14 dias. Retorno urgente se febre, dor intensa, sangramento abundante.',
    referencias: 'AAGL Guidelines on Distension Media for Hysteroscopy 2022. Loffer et al., Fluid management for hysteroscopy. JMIG 2017. Muzii et al., Hysteroscopic treatment of endometrial polyps. Fertil Steril 2018.',
  },
  {
    especialidade: 'Ginecologia',
    nome: 'Colpoperineoplastia (Prolapso)',
    tempos: '1. Litotomia; 2. Incisão vaginal e plicatura de fáscias.',
    tecnica: 'Raquianestesia em sela (T10) provê relaxamento esfincteriano perineal absoluto.',
    problemas: 'Hemorragia de plexos pélvicos. Lesão isquêmica de nervos lombo-sacros (perneiras longas).',
    correcoes: 'Movimentar ambas as pernas simultaneamente nos estribos para evitar luxação sacroilíaca.',
    posOp: 'Retenção urinária pós-operatória. Paracetamol + Opioide fraco.',
    referencias: 'Ljungqvist et al., ERAS Pelvic Organ Prolapse.',
  },

  // ── OFTALMOLOGIA ──────────────────────────────────────────
  {
    especialidade: 'Oftalmologia',
    nome: 'Facoemulsificação, Refrativa e Exéreses (Pterígio/Calázio)',
    tempos: '1. Laser ou ultrassom sob campo visual restrito (microscópio).',
    tecnica: 'Tópica (Colírios) + Sedação Ultraleve (MAC). Calázio pediátrico: Geral curta.',
    problemas: 'Apneia seguida de sobressalto no microscópio (rompendo a cápsula do cristalino); Claustrofobia.',
    correcoes: 'Doses mínimas ("Less is more"). Fornecer O2 sob o campo cirúrgico para varrer o CO2.',
    posOp: 'Alta em minutos. Gelo local.',
    referencias: 'Kumar et al., Local anaesthesia for cataract.',
  },
  {
    especialidade: 'Oftalmologia',
    nome: 'Vitrectomia, Retinopexia e Trabeculectomia',
    tempos: '1. Acesso intraocular; 2. Peeling macular/injeção de gás ou buckle escleral.',
    tecnica: 'Bloqueio Peribulbar ou Geral. Controle estrito de PIO (Glaucoma).',
    problemas: 'Interação N2O-Gás letal; Reflexo Oculocardíaco (bradicardia); NVPO intensa.',
    correcoes: 'PROIBIÇÃO de N2O mín. 15 minutos antes da injeção de gás SF6/C3F8. Tratar bradicardia com alívio da tração e Atropina.',
    posOp: 'Face-down pós-op (Gás). Dor severa no Scleral Buckle (Cetorolaco IV).',
    referencias: 'Seaberg et al., Ophthalmic Surgery.',
  },
  {
    especialidade: 'Oftalmologia',
    nome: 'Transplante de Córnea e Dacriocistorrinostomia',
    tempos: '1. Trepanação ("Globo Aberto") ou osteotomia nasal.',
    tecnica: 'Geral IOT com controle absoluto de tosse. DCR exige tubo RAE.',
    problemas: 'Globo Aberto: Extubação com tosse gera Hemorragia Expulsiva Supracoroidal (cegueira). Sangramento nasal na DCR.',
    correcoes: 'Deep Extubation (plano profundo) ou Dexmedetomidina/Lidocaína garantem despertar "liso" e seguro. DCR requer tampão faríngeo.',
    posOp: 'Supino estrito. Prevenção de tosse e vômito obrigatória.',
    referencias: 'Guidelines for Perioperative Management of Open Globe.',
  },
  {
    especialidade: 'Oftalmologia',
    nome: 'Cirurgia de Estrabismo e Blefaroplastia',
    tempos: '1. Tração de músculos extraoculares ou excisão de gordura palpebral.',
    tecnica: 'Estrabismo: Geral (Pediatria). Blefaroplastia: Local + MAC.',
    problemas: 'Reflexo Oculocardíaco (ROC > 90% em estrabismo); Hematoma retrobulbar iatrogênico na blefaroplastia.',
    correcoes: 'Atropina profilática na indução pediátrica. Avaliar clinicamente sinais de tensão orbitária.',
    posOp: 'NVPO maciça no estrabismo (Profilaxia com Dexa+Ondansetrona).',
    referencias: 'Blanc et al., The Oculocardiac reflex.',
  },

  // ── CIRURGIA PLÁSTICA ─────────────────────────────────────
  {
    especialidade: 'Cirurgia Plástica',
    nome: 'Mamoplastia (Aumento, Redutora) e Ritidoplastia (Face)',
    tempos: '1. Incisão; 2. Descolamento SMAS/muscular; 3. Ressecção/Implantes.',
    tecnica: 'Geral TIVA obrigatória (melhor padrão para evitar NVPO).',
    problemas: 'Altíssima incidência NVPO; Dor submuscular peitoral; Hematoma de SMAS expandindo.',
    correcoes: 'PECS Block ecoguiado (Reduz 70% opioides 1A). Hipotensão permissiva controlada para hemostasia facial fina.',
    posOp: 'Prevenção tripla NVPO. Elevação da cabeceira no Lifting.',
    referencias: 'Blanco et al., The PECS block.',
  },
  {
    especialidade: 'Cirurgia Plástica',
    nome: 'Lipoaspiração, Abdominoplastia e Gluteoplastia (BBL)',
    tempos: '1. Infiltração Tumescente; 2. Aspiração; 3. Lipoenxertia glútea/Plicatura abdominal.',
    tecnica: 'Geral ou Peridural. Prevenção máxima contra TVP.',
    problemas: 'Embolia de Gordura Letal no BBL (intramuscular); Risco maciço de TEP (Abdominoplastia); LAST da lidocaína.',
    correcoes: 'Limite Lidocaína ASPS: 35 mg/kg. Lipoenxertia: APENAS subcutânea. Heparina profilática (Escore Caprini > 7).',
    posOp: 'TAP block para a plicatura muscular. Proibido sentar no BBL.',
    referencias: 'Mofid et al., ASERF Fat Grafting. ASPS VTE Task Force.',
  },
  {
    especialidade: 'Cirurgia Plástica',
    nome: 'Ninfoplastia, Ginecomastia e Otoplastia',
    tempos: '1. Excisão labial, glândula mamária ou cartilagem auricular.',
    tecnica: 'Local + Sedação MAC (Ambulatorial) ou Raquianestesia em sela (Ninfoplastia).',
    problemas: 'Dor por bloqueio insuficiente da glândula mamária (nervo intercostal profundo).',
    correcoes: 'Aguardar tempo de latência após infiltração profunda ou suportar com Alfentanil.',
    posOp: 'Day-clinic. Uso de cintas e capacete compressivo.',
    referencias: 'ASPS Practice Advisories.',
  },

  // ── CIRURGIA VASCULAR ─────────────────────────────────────
  {
    especialidade: 'Cirurgia Vascular',
    nome: 'Endarterectomia Carotídea e Bypass Periférico',
    tempos: '1. Clampeamento vascular e remoção de placa ateromatosa/derivação.',
    tecnica: 'Carótida: Regional (Bloqueio Superficial + Profundo de Plexo Cervical C2-C4 com Ropivacaína 0,5%) — vantagem de monitorização neurológica do paciente acordado (padrão-ouro para detecção isquemia). Geral equivalente em desfechos (GALA Trial). Indução geral cuidadosa: Etomidato 0,2 mg/kg ou Propofol 1 mg/kg + Fentanil 2–3 mcg/kg — evitar hipotensão (perigo de isquemia ipsilateral). PAI punho radial ipsilateral ao lado da cirurgia. EEG processado (BIS) ou NIRS bilateral útil para monitorização de perfusão cerebral. Bypass periférico: Raquianestesia prolongada (Bupivacaína 0,5% 15 mg + Morfina 0,1 mg intratecal) para vasodilatação simpática e melhora do fluxo distal.',
    problemas: 'Isquemia Cerebral no clampe carotídeo (incidência 5–10% sem shunt); IAM perioperatório (comorbidade coronária associada); Hematoma cervical compressivo pós-op (emergência de via aérea); Lesão do Nervo Hipoglosso ou Laríngeo Recorrente; Embolia cerebral por placa ateromatosa durante dissecção; Síndrome de Hiperperfusão Carotídea (hipertensão + cefaleia + convulsão 24–72 h pós-op); Trombose precoce do enxerto de bypass; Reestenose tardia.',
    correcoes: 'Isquemia Cerebral (paciente acordado): agitação/déficit neurológico → colocar shunt cirúrgico imediatamente. Geral: queda de NIRS > 20% → aumentar PAM > 20% acima do basal (Fenilefrina ou Efedrina), shunt se persistir. Heparinização: 100 UI/kg antes do clampe, TCA alvo > 250 s. Desclampeamento: reduzir PAM gradualmente, nitroglicerina sublingual se hipertensão súbita. Hematoma Cervical pós-op: abertura cirúrgica IMEDIATA em leito de UTI ou BO — não tentar IOT com hematoma expansivo (via aérea distorcida → cricotireoidotomia de emergência). Síndrome Hiperperfusão: controle estrito PA < 140/90 mmHg por 48–72 h.',
    posOp: 'Unidade de AVC ou UTI pós-Endarterectomia por 12–24 h: monitorização neurológica horária (força, fala, consciência), controle rigoroso de PA (sistólica 120–160 mmHg). Risco máximo de hematoma cervical nas primeiras 6 h (manter dreno de sucção). Duplex carotídeo em D1 pós-op. Analgesia: Paracetamol 1 g/6 h + AINEs (Ibuprofeno 400 mg 8/8 h) + Dipirona 1 g/8 h; evitar opioides para facilitar exame neurológico. Dupla antiagregação (AAS + Clopidogrel) mantida perioperatória conforme protocolo. Alta D2–D3 se estável.',
    referencias: 'GALA Trial (General Anaesthesia vs. Local Anaesthesia for Carotid Surgery). Lancet 2008. AHA/ASA Carotid Endarterectomy Guidelines 2021. Rothwell et al., Benefit of carotid endarterectomy versus stenting. Lancet 2016.',
  },
  {
    especialidade: 'Cirurgia Vascular',
    nome: 'Reparo Aneurisma de Aorta (Aberta/EVAR)',
    tempos: '1. Laparotomia retroperitoneal (Aberta) ou acesso femoral escópico (EVAR).',
    tecnica: 'Aberta: Geral IOT + Peridural Torácica Baixa (T9–T11) — combinada permite redução de opioides e extubação precoce. PAI punho radial, CVC jugular, Swan-Ganz ou PiCCO para monitorização de DC. Acesso periférico 14G x2. Indução suave: Etomidato 0,2–0,3 mg/kg ou Propofol + Fentanil + Rocurônio. Aquecimento ativo desde a indução. Heparinização 100 UI/kg antes do clampe aórtico. EVAR: MAC (Dexmedetomidina + Fentanil) ou Raquianestesia (Bupivacaína hiperbárica 12,5 mg) com acesso femoral; PAI obrigatória; proteção renal com manitol + hidratação pré-contraste.',
    problemas: 'Choque de Desclampeamento Aórtico (vasodilatação isquêmica reperfusional — hipotensão grave); Nefropatia por contraste (EVAR); Embolia Ateromatosa distal (síndrome do dedo azul); Isquemia Intestinal por clampe da artéria mesentérica inferior; Isquemia Medular (rara em AAA infrarrenal, maior em toracoabdominal); Coagulopatia dilucional/hiperfibrinólise; Reação Anafilática ao contraste iodado; Lesão de veia cava.',
    correcoes: 'Desclampeamento Aórtico: avisar cirurgião 3 min antes → repor volume 500 mL cristaloide, ter Noradrenalina ou Fenilefrina em seringa, soltar clamp LENTAMENTE em 5–10 min; bólus de Cálcio (Gluconato 1 g IV) se colapso. Nefropatia contraste: hidratação com NaCl 0,9% 1 mL/kg/h por 6 h pré e 6 h pós contraste; N-acetilcisteína 600 mg 12/12 h 24 h antes. Coagulopatia: TEG/ROTEM guiado; TXA 1 g profilático; Fibrinogênio se < 1,5 g/L; Plaquetas se < 50.000 com sangramento. Reação contraste: Adrenalina 0,5 mg IM + corticoide + anti-histamínico.',
    posOp: 'Extubação precoce (< 4 h pós-op) se hemodinâmica estável, normotérmico e gasometria aceitável. Analgesia peridural contínua Ropivacaína 0,2% + Fentanil 2 mcg/mL a 5–8 mL/h (aberta) — mantida 48–72 h. EVAR: alta acelerada (D1–D2), analgesia oral simples. Monitorar MMII: pulsos pediais horários nas primeiras 6 h. Diurese ≥ 0,5 mL/kg/h. Creatinina D1 e D3. Vigilância de sinais de isquemia intestinal: dor abdominal, febre, leucocitose. Duplex de MMII para embolia distal.',
    referencias: 'SVS Practice Guidelines AAA 2018. de Bruin et al., Endovascular vs open repair for elective AAA. NEJM 2010. Chaikof et al., SVS reporting standards for aortic aneurysm repair. J Vasc Surg 2009.',
  },
  {
    especialidade: 'Cirurgia Vascular',
    nome: 'Trombectomia/Embolectomia (Fogarty) e Amputação Maior',
    tempos: 'Emergência (Salvamento). Passagem de cateter Fogarty intrarterial ou osteotomia transfemoral.',
    tecnica: 'Raqui, Local ou Geral (depende urgência). Amputação: Bloqueios Nervosos (Isquiático/Femoral).',
    problemas: 'Síndrome de Reperfusão letal (Potássio e mioglobina no coração na desobstrução). Dor do Membro Fantasma.',
    correcoes: 'Ketamina intra-op e Cateter Contínuo reduzem Dor Fantasma (1B). Bicarbonato/Cálcio profilático antes da reperfusão.',
    posOp: 'UTI. Fasciotomia frequente por Síndrome Compartimental no reperfundido.',
    referencias: 'ASRA Pain Medicine Guidelines.',
  },
  {
    especialidade: 'Cirurgia Vascular',
    nome: 'Fístula Arteriovenosa, Varizes, Filtro de Veia Cava e Angioplastia',
    tempos: '1. Termoablação a Laser (Varizes), Anastomose de FAV, implante endovascular.',
    tecnica: 'Varizes: Tumescente Pura. FAV: Bloqueio Supraclavicular ecoguiado.',
    problemas: 'Queimadura de Laser (nervo safeno); DRC hipercalêmica na FAV; Falência respiratória no Filtro de VCI.',
    correcoes: 'Bloqueio de Plexo gera simpatectomia e vasodilatação que garante maturidade da FAV (Nível 1A).',
    posOp: 'Ambulatorial. Proteger FAV de punções venosas na enfermaria.',
    referencias: 'KDOQI Vascular Access Guidelines.',
  },
];
