export interface GuiaCirurgico {
  especialidade: string;
  nome: string;
  tempos: string;
  tecnica: string;
  problemas: string;
  correcoes: string;
  posOp: string;
  referencias: string;
}

export const ESPECIALIDADES = [
  'Cirurgia Cardíaca',
  'Urologia',
  'Cirurgia Torácica',
  'Ortopedia',
  'Otorrinolaringologia',
  'Neurocirurgia',
  'Ginecologia',
  'Oftalmologia',
  'Cirurgia Plástica',
  'Cirurgia Vascular',
] as const;

export type Especialidade = typeof ESPECIALIDADES[number];

export const BANCO_CIRURGIAS: GuiaCirurgico[] = [
  // ── CIRURGIA CARDÍACA ──────────────────────────────────────
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Revascularização do Miocárdio (CRM) com CEC',
    tempos: '1. Esternotomia; 2. Dissecção de enxertos; 3. Heparinização; 4. CEC; 5. Clampeamento/anastomoses; 6. Saída CEC; 7. Protamina.',
    tecnica: 'Geral Balanceada/TIVA (MYRIAD Trial 1A). ETE obrigatório (SCA/ASA).',
    problemas: 'Vasoplegia Pós-CEC (SIRS); Resposta à esternotomia; Coagulopatia.',
    correcoes: 'Vasoplegia: Noradrenalina (0,05–0,5 mcg/kg/min). Heparina (300–400 UI/kg), TCA alvo > 480s. Reversão: 1mg Protamina/100 UI Heparina.',
    posOp: 'ERAS Cardiac: Extubação precoce (<6h). Bloqueio ESP poupador de opioide.',
    referencias: 'Engelman et al., 2019 (ERAS Cardiac).',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Substituição/Reparação Valvular e TAVI',
    tempos: 'TAVI: 1. Acesso vascular; 2. Rapid Pacing; 3. Implante. Aberta: 1. Esternotomia; 2. CEC; 3. Troca valvar.',
    tecnica: 'TAVI: MAC/Sedação Consciente (SOLVE-TAVI). Aberta: Geral com ETE 3D.',
    problemas: 'Hipotensão grave (miocárdio isquêmico); BAV total no TAVI.',
    correcoes: 'Manter FC 60–70 bpm (Fenilefrina). Rapid Pacing: Adrenalina se parada refratária.',
    posOp: 'Observação UTI. Alta precoce (1–3 dias) para TAVI.',
    referencias: 'Otto et al., ACC/AHA Valvular Guidelines 2020.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Correção de Aneurisma da Aorta (Aberta e TEVAR)',
    tempos: 'TEVAR: Acesso femoral, endoprótese. Aberta: Esternotomia, CEC com Hipotermia Profunda, Tubo Dacron.',
    tecnica: 'TEVAR: Regional, MAC ou Geral. Aberta: Geral complexa, NIRS obrigatório.',
    problemas: 'Isquemia Medular (Paraplegia); Vasoplegia e Sangramento Maciço na CEC.',
    correcoes: 'Dreno de LCR para proteção medular (PIC < 10 mmHg). Protocolo de transfusão maciça guiado por TEG/ROTEM.',
    posOp: 'Monitorização neurológica horária de extremidades inferiores.',
    referencias: 'Isselbacher et al., 2022 ACC/AHA Aortic Disease.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Cirurgia de Cardiopatias Congênitas (ex: Fallot)',
    tempos: '1. Esternotomia; 2. CEC; 3. Ressecção de obstruções e fechamento de CIV; 4. Saída de CEC.',
    tecnica: 'Indução inalatória/venosa. Evitar bolhas de ar nos acessos (risco de embolia paradoxal).',
    problemas: 'Crise de Hipóxia (Spells); Disfunção Aguda de VD pós-CEC.',
    correcoes: 'Crises: FiO2 100%, volume, Fenilefrina. Evitar inotrópicos que espasam o VD. VD falido: Milrinona e iNO.',
    posOp: 'UTI Pediátrica. Analgesia com parasternal block.',
    referencias: 'Stout et al., 2018 AHA/ACC Congenital Heart Disease.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Transplante Cardíaco Ortotópico',
    tempos: '1. Reesternotomia; 2. CEC; 3. Cardiectomia; 4. Anastomoses; 5. Reperfusão.',
    tecnica: 'Indução cautelosa preservando estabilidade (Etomidato/Fentanil). ETE.',
    problemas: 'Coração Denervado (sem resposta vagal); Falência primária do enxerto de VD.',
    correcoes: 'Bradicardia: Agonistas diretos (Isoproterenol 0,01–0,05 mcg/kg/min) ou marcapasso. Proteção VD com hiperventilação leve e iNO.',
    posOp: 'Isolamento reverso estrito. Imunossupressão.',
    referencias: 'ISHLT Guidelines for heart transplant recipients.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Cirurgia para Arritmias (Procedimento de Maze)',
    tempos: '1. Linhas de ablação (crio/RF) em veias pulmonares; 2. Exclusão de auriculeta; 3. Cirurgia valvar base.',
    tecnica: 'Geral com ETE obrigatório para avaliar trombos em apêndice atrial.',
    problemas: 'Lesão térmica do esôfago (fístula) ou nervo frênico; BAV total pós-ablação.',
    correcoes: 'Monitorização de temperatura esofágica contínua (<15 °C ou >39 °C → pausa). Marcapasso epicárdico de prontidão.',
    posOp: 'Telemetria em UTI. Manutenção de antiarrítmicos (Amiodarona).',
    referencias: 'Calkins et al., HRS/EHRA Consensus on Atrial Fibrillation.',
  },
  {
    especialidade: 'Cirurgia Cardíaca',
    nome: 'Implantação de Dispositivos (Pacemakers e CDI)',
    tempos: '1. Punção venosa; 2. Passagem de eletrodos sob escopia; 3. Teste de limiar; 4. Confecção de loja.',
    tecnica: 'Sedação (MAC) com Propofol/Dexmedetomidina + Anestesia Local.',
    problemas: 'Teste de Desfibrilação (indução de FV); Pneumotórax; Tamponamento cardíaco.',
    correcoes: 'Aprofundar sedação antes do choque do CDI. Ter pás externas coladas. Pericardiocentese se tamponamento.',
    posOp: 'Raio-X de tórax pós-operatório. Restrição de movimento do braço.',
    referencias: 'Kusumoto et al., ACC/AHA Bradycardia Guidelines.',
  },

  // ── UROLOGIA ──────────────────────────────────────────────
  {
    especialidade: 'Urologia',
    nome: 'Ressecção Transuretral da Próstata (RTU-P)',
    tempos: '1. Litotomia; 2. Ressectoscópio; 3. Ressecção sob irrigação contínua.',
    tecnica: 'Raquianestesia (T10) padrão-ouro para monitorização neurológica acordada.',
    problemas: 'Síndrome de RTU (intoxicação hídrica por glicina); Perfuração vesical.',
    correcoes: 'Tratamento RTU: Furosemida (20–40 mg), restrição hídrica. Salina hipertônica 3% lenta se Na⁺ < 120 sintomático.',
    posOp: 'Anticolinérgicos (Oxibutinina) para espasmo vesical.',
    referencias: 'EAU Guidelines on Non-Neurogenic LUTS.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Prostatectomia Radical (Robótica/Laparoscópica)',
    tempos: '1. Trendelenburg extremo (>30°); 2. Pneumoperitônio; 3. Exérese; 4. Anastomose.',
    tecnica: 'Geral IOT. Bloqueio neuromuscular profundo (PTC 1–2). Restrição hídrica severa.',
    problemas: 'Edema facial/via aérea; Aumento de PIC e redução de complacência pulmonar.',
    correcoes: 'Manter fluidos restritos (<1,5 L) até a anastomose para não obscurecer o campo com urina. Leak Test pré-extubação.',
    posOp: 'ERAS: TAP block ecoguiado. Alta precoce sem opioides sistêmicos.',
    referencias: 'Ljungqvist et al., ERAS Pelvic Surgery.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Nefrectomia (Total ou Parcial)',
    tempos: '1. Posição de flanco; 2. Clampeamento hilar; 3. Ressecção.',
    tecnica: 'Geral Balanceada. Cuidado extremo no posicionamento em quebra (kidney rest).',
    problemas: 'Injúria isquêmica ao rim remanescente (parcial); Lesão de plexo braquial.',
    correcoes: 'Proteção renal: Manitol (12,5–25 g IV) antes do clampeamento isquêmico. Euvolemia estrita.',
    posOp: 'TAP Block subcostal, QLB ou ESP Block (T8).',
    referencias: 'ERAS Society Radical Nephrectomy.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Cirurgias de Cálculo (Ureterolitotripsia e NLPC)',
    tempos: 'Uretero: Litotomia, laser. NLPC: Prono, punção lombar percutânea, dilatação e litotripsia.',
    tecnica: 'Uretero: Raqui ou Geral. NLPC: Geral IOT obrigatória (decúbito prono).',
    problemas: 'NLPC: Alta absorção de fluidos/hipotermia; Pneumotórax na punção acima da 12ª costela.',
    correcoes: 'Controle térmico agressivo. Aumento súbito da pressão de pico no ventilador indica pneumotórax (checar USG).',
    posOp: 'Infiltração de trajeto da nefrostomia ou bloqueio intercostal.',
    referencias: 'EAU Guidelines on Urolithiasis.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Vasectomia e Correção de Varicocele',
    tempos: '1. Infiltração local/bloqueio de cordão; 2. Excisão/ligadura de vasos ou deferentes.',
    tecnica: 'Local com Sedação Leve (MAC). Microcirurgia de varicocele exige imobilidade (Raquianestesia opcional).',
    problemas: 'Reflexo Vagal intenso (bradicardia/hipotensão) pela tração do cordão espermático.',
    correcoes: 'Pausar estímulo. Atropina (0,5 mg) se necessário.',
    posOp: 'Ambulatorial. Analgesia oral simples, suspensório escrotal.',
    referencias: 'AUA Guideline Vasectomy.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Postectomia (Circuncisão)',
    tempos: '1. Antissepsia; 2. Bloqueio peniano; 3. Excisão do prepúcio.',
    tecnica: 'Pediatria: Geral (ML) + Bloqueio Peniano. Adultos: Local ou Raqui em sela.',
    problemas: 'LAST ou isquemia tecidual grave por uso errôneo de vasoconstritor.',
    correcoes: 'NUNCA usar epinefrina no bloqueio peniano (usar Bupivacaína ou Ropivacaína pura).',
    posOp: 'Alta imediata. Cuidado com retenção urinária por curativo apertado.',
    referencias: 'Coté & Lerman Pediatric Anesthesia.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Cistectomia Radical com Derivação',
    tempos: '1. Exérese de bexiga e linfonodos; 2. Confecção de neobexiga/conduto ileal com alça intestinal.',
    tecnica: 'Geral + GDFT (Terapia Guiada por Metas). PAI obrigatória. Monitorização de débito cardíaco contínuo.',
    problemas: 'Perda sanguínea maciça; Acidose hiperclorêmica pela alça ileal; Hipotensão grave se uso de peridural.',
    correcoes: 'Uso de baixas doses de Noradrenalina para manter PA e perfusão da anastomose intestinal, evitando hiper-hidratação.',
    posOp: 'TAP Block contínuo substituiu a Peridural Torácica para estabilidade hemodinâmica (ERAS).',
    referencias: 'Cerantola et al., ERAS Society Radical Cystectomy.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Cirurgia de Sling (TVT/TOT)',
    tempos: '1. Litotomia; 2. Incisão vaginal; 3. Passagem de fita retropúbica/transobturatória.',
    tecnica: 'Raquianestesia, MAC ou Geral. Raqui (T10) provê relaxamento de assoalho ideal.',
    problemas: 'Perfuração vesical (TVT) e sangramento de plexos pélvicos.',
    correcoes: 'Cistoscopia intraoperatória mandatória após a passagem da agulha no TVT.',
    posOp: 'Retenção urinária por hipercorreção da fita.',
    referencias: 'AUA/SUFU Guideline Female Stress Urinary Incontinence.',
  },
  {
    especialidade: 'Urologia',
    nome: 'Orquiectomia',
    tempos: 'Radical (câncer): Incisão inguinal, clampeamento alto. Simples: Escrotal.',
    tecnica: 'Raquianestesia, Bloqueio Ilioinguinal ou Geral (se metástase pulmonar).',
    problemas: 'Risco de toxicidade pulmonar (SDRA) se o paciente usou quimioterapia com Bleomicina prévia.',
    correcoes: 'Regra Bleomicina: Manter FiO2 a mais baixa possível (SpO2 > 90–92%) e fluidos restritivos para evitar dano alveolar.',
    posOp: 'TAP Block ilioinguinal para técnica radical.',
    referencias: 'EAU Guidelines on Testicular Cancer.',
  },

  // ── CIRURGIA TORÁCICA ─────────────────────────────────────
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Lobectomia Pulmonar e Segmentectomia',
    tempos: '1. Decúbito lateral; 2. Isolamento pulmonar; 3. Grampeamento vascular/brônquico.',
    tecnica: 'Geral com Ventilação Monopulmonar (Tubo de Duplo Lúmen). Restrição fluídica (<1,5 mL/kg/h).',
    problemas: 'Hipoxemia (shunt do pulmão colapsado); Lesão Pulmonar Induzida pelo Ventilador (VILI).',
    correcoes: 'Tratar hipoxemia com CPAP no pulmão operado e PEEP no ventilado. Volume corrente 5–6 mL/kg predito.',
    posOp: 'PVB (Paravertebral) ou ESP block são padrão-ouro (ERAS).',
    referencias: 'Batchelor et al., ERAS Lung Surgery.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Pneumonectomia',
    tempos: '1. Lateral; 2. VMP; 3. Ligadura de artéria pulmonar principal; 4. Remoção do pulmão.',
    tecnica: 'Geral VMP com TDL contralateral. PAI e acesso central obrigatórios.',
    problemas: 'Edema Pulmonar Pós-Pneumonectomia (alta mortalidade); Disfunção de VD aguda.',
    correcoes: 'Restrição hídrica drástica (usar vasopressor em vez de fluido). Milrinona/iNO se VD falir.',
    posOp: 'Posicionamento deitado sobre o lado operado. UTI.',
    referencias: 'Slinger et al., Thoracic Anesthesia.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Decorticação Pulmonar e Pleurodese',
    tempos: '1. VATS/Aberta; 2. Remoção de casca fibrótica (empiema) ou talcagem (pleurodese).',
    tecnica: 'Geral com VMP. PAI rotina na decorticação.',
    problemas: 'Sangramento torácico maciço (decorticação); Dor pleurítica excruciante e SIRS (talcagem).',
    correcoes: 'Ácido Tranexâmico 1–2 g profilático. Infiltração pleural direta com Bupivacaína antes do talco.',
    posOp: 'Peridural torácica essencial na decorticação aberta. Proibido AINEs após pleurodese.',
    referencias: 'British Thoracic Society Pleural Disease Guideline.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Mediastinoscopia Cervical',
    tempos: '1. Incisão supraesternal; 2. Dissecção pré-traqueal; 3. Biópsia linfonodal.',
    tecnica: 'Geral com Tubo simples (aramado opcional).',
    problemas: 'Compressão do Tronco Braquiocefálico (isquemia cerebral); Hemorragia de grandes vasos.',
    correcoes: 'MANDATÓRIO oximetria/PAI no braço direito para detectar compressão. Acesso calibroso no braço esquerdo/perna.',
    posOp: 'Observar pneumotórax ou lesão de nervo laríngeo recorrente.',
    referencias: 'Choen\'s Thoracic Anesthesia.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Timectomia e Simpatectomia',
    tempos: '1. VATS/Robótica; 2. Ressecção do timo (Miastenia) ou ablação de gânglio simpático.',
    tecnica: 'Timectomia: Geral, TIVA preferida. Simpatectomia: Geral com Tubo simples e capnotórax seletivo.',
    problemas: 'Miastenia: Sensibilidade extrema a bloqueadores neuromusculares. Simpatectomia: Bradicardia vagal profunda pelo CO2.',
    correcoes: 'Timectomia: Evitar relaxante, ou reverter 100% com Sugammadex (Nível A). Simpatectomia: Pausar CO2 se hipotensão aguda.',
    posOp: 'Critérios estritos de extubação em miastênicos.',
    referencias: 'Gilhus et al., Myasthenia gravis. N Engl J Med.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Correção de Parede Torácica (Pectus Excavatum – Nuss)',
    tempos: '1. VATS direita; 2. Passagem retroesternal de barra curva; 3. Rotação elevando o esterno.',
    tecnica: 'Geral IOT. Ecocardiograma prévio obrigatório.',
    problemas: 'Transfixação letal do coração pela barra; Dor osteoarticular extrema.',
    correcoes: 'Desconectar ventilação durante a passagem do guia para afastar o coração do esterno.',
    posOp: 'Mudança de Paradigma: Crioablação Intercostal substituiu a peridural (Nível 1A) com alta precoce.',
    referencias: 'Graves et al., Cryoanalgesia in Nuss Procedure.',
  },
  {
    especialidade: 'Cirurgia Torácica',
    nome: 'Transplante Pulmonar',
    tempos: '1. Toracotomia/Clamshell; 2. Pneumonectomia; 3. Anastomoses do doador.',
    tecnica: 'Geral Complexa. TDL, PAI, MAC e ETE obrigatórios. ECMO de prontidão.',
    problemas: 'Disfunção Primária do Enxerto (isquemia-reperfusão); Colapso de VD.',
    correcoes: 'Suporte intraoperatório com ECMO VA ou VV reduziu mortalidade (Nível B). Reperfusão lenta com FiO2 baixa (<40%).',
    posOp: 'UTI. Imunossupressão (Metilprednisolona intraop).',
    referencias: 'Machuca et al., ECMO in Lung Transplantation.',
  },

  // ── ORTOPEDIA ─────────────────────────────────────────────
  {
    especialidade: 'Ortopedia',
    nome: 'Artroplastia Total de Quadril e Joelho',
    tempos: '1. Acesso articular; 2. Cortes/Fresagem óssea; 3. Implante com/sem cimento.',
    tecnica: 'Raquianestesia T10 fortemente recomendada (PROSPECT 1A). Diminui TVP e perda sanguínea.',
    problemas: 'Síndrome de Implantação do Cimento (BCIS) causa hipotensão/embolia. Dor do torniquete em ATJ.',
    correcoes: 'Tratamento BCIS: O2 100% preventivo, expansão volêmica e Adrenalina. TXA IV/tópico para sangramento.',
    posOp: 'ATJ: Adductor Canal Block (ACB) preferido ao femoral. ATQ: PENG Block ecoguiado.',
    referencias: 'Memtsoudis et al., ERAS Total Joint Arthroplasty.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Artroscopia de Joelho e Reconstrução de LCA',
    tempos: '1. Garrote; 2. Retirada de enxerto tendíneo; 3. Fixação via túneis ósseos.',
    tecnica: 'Raquianestesia de curta duração (Cloroprocaína/Bupi baixas doses) ou Geral rápida.',
    problemas: 'Dor inibitória reflexa do quadríceps (pela coleta do enxerto patelar).',
    correcoes: 'Bloqueio Femoral ou iPACK ecoguiado, infiltração local.',
    posOp: 'Day-clinic. Crioterapia agressiva pós-op.',
    referencias: 'Lavoie-Gagne et al., Pain Control in ACL.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Reparo de Manguito Rotador / Artroscopia de Ombro',
    tempos: '1. Cadeira de Praia (Beach Chair) ou Lateral; 2. Portais; 3. Sutura com âncoras.',
    tecnica: 'Geral IOT combinada com Bloqueio de Plexo Braquial.',
    problemas: 'Isquemia cerebral (posição sentada); Reflexo de Bezold-Jarisch (bradicardia e hipotensão).',
    correcoes: 'Manter PAM ajustada para altura da cabeça. Efedrina se Bezold-Jarisch.',
    posOp: 'Bloqueio Interescalênico (padrão-ouro), MAS contraindicado se DPOC grave (paralisa frênico).',
    referencias: 'Rains et al., Position-related complications.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Liberação do Túnel do Carpo',
    tempos: '1. Incisão tenar; 2. Secção do ligamento carpal.',
    tecnica: 'Técnica WALANT (Lidocaína+Epinefrina acordado) sem garrote. Ou Bloqueio de Bier.',
    problemas: 'Mito sobre necrose de extremidades com adrenalina foi refutado.',
    correcoes: 'Se isquemia digital persistir, usar Fentolamina local.',
    posOp: 'Analgesia simples oral.',
    referencias: 'Lalonde et al., Wide awake hand surgery.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Artrodese de Coluna Lombar / Discectomia',
    tempos: '1. Decúbito prono; 2. Parafusos pediculares; 3. Laminectomia/Cages.',
    tecnica: 'Geral TIVA se uso de PEM (Potencial Evocado Motor). Relaxante proibido após indução.',
    problemas: 'POVL (Neuropatia Óptica Isquêmica); Sangramento maciço do plexo de Batson se compressão abdominal.',
    correcoes: 'Abdome pendular/livre na mesa. Cabeça neutra. Manter PAM e evitar anemia intraoperatória.',
    posOp: 'Extubação sem tosse se reparo de dura-máter intra-op. Ketamina para evitar hiperalgesia do Remifentanil.',
    referencias: 'ASA Task Force on Perioperative Visual Loss.',
  },
  {
    especialidade: 'Ortopedia',
    nome: 'Osteossíntese e Fixação Externa (Trauma)',
    tempos: '1. Fresagem de canal (reaming); 2. Inserção de hastes/placas ou fixadores em damage control.',
    tecnica: 'Membros inferiores: Raquianestesia. Membros superiores: Bloqueio Supraclavicular. Trauma grave: Geral RSI.',
    problemas: 'Embolia Gordurosa (queda súbita de EtCO2 na inserção da haste intramedular); Tríade letal do trauma.',
    correcoes: 'Tratamento Embolia Gordurosa: Suporte O2/Ventilatório 100%. Protocolo transfusão maciça (1:1:1) e TXA 1 g.',
    posOp: 'Bloqueios devem considerar o risco de mascarar Síndrome Compartimental aguda em fraturas fechadas.',
    referencias: 'ATLS Guidelines 10th Edition.',
  },

  // ── OTORRINOLARINGOLOGIA ──────────────────────────────────
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Amigdalectomia, Adenoidectomia e Miringotomia',
    tempos: '1. Abridor de boca; 2. Eletrocautério/frio. Miringotomia: incisão e tubo de ventilação.',
    tecnica: 'Geral IOT (Tubo RAE preformado). Miringotomia: Inalatória sob máscara facial.',
    problemas: 'Sangramento pós-op (mascarado por deglutição); Altíssima taxa de NVPO.',
    correcoes: 'Profilaxia dupla: Dexa + Ondansetrona. Indução Rápida se reabordagem por sangramento (estômago cheio).',
    posOp: 'ALERTA FDA: Proibido Codeína/Tramadol em < 12 anos. Usar Ibuprofeno (seguro em metanálise) e Paracetamol.',
    referencias: 'FDA Drug Safety Communication regarding Codeine.',
  },
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Septoplastia, Turbinectomia e FESS (Sinusectomia)',
    tempos: '1. Infiltração vasoconstritora; 2. Endoscopia nasossinusal/ressecção.',
    tecnica: 'Geral TIVA (Padrão 1A para FESS) para melhorar campo visual e reduzir sangramento.',
    problemas: 'Toxicidade sistêmica por adrenalina local (taquicardia/hipertensão); Lesão de base de crânio/órbita.',
    correcoes: 'Dose de adrenalina máx 5–7 mcg/kg. Controle de PA/FC estrito (Hipotensão controlada com Beta-bloqueador).',
    posOp: 'Despertar suave (Dexmedetomidina ou Deep Extubation) para evitar tosse e epistaxe no extubar.',
    referencias: 'Wormald et al., TIVA vs Inhalational in FESS.',
  },
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Timpanoplastia e Mastoidectomia',
    tempos: '1. Fresagem óssea; 2. Enxerto timpânico.',
    tecnica: 'Geral Balanceada/TIVA. Relaxante neuromuscular restrito se uso de monitorização do nervo facial.',
    problemas: 'Expulsão do enxerto timpânico por expansão de gás.',
    correcoes: 'REGRA: Proibido o uso de Óxido Nitroso (N2O) na fixação do enxerto (expande na câmara fechada).',
    posOp: 'Terapia NVPO agressiva. Evitar vômito pós-operatório.',
    referencias: 'Eisele et al., Nerve monitoring.',
  },
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Microcirurgia de Laringe',
    tempos: '1. Laringoscopia de suspensão; 2. LASER de corda vocal.',
    tecnica: 'Geral com Tubo seguro para Laser (MLT) ou Jet Ventilation. Via aérea compartilhada.',
    problemas: 'Incêndio na Via Aérea (Airway Fire); Reflexo autônomo severo à suspensão.',
    correcoes: 'Algoritmo Incêndio (ASA): FiO2 < 30%, usar ar comprimido. Sem N2O. Balonete insuflado com soro + azul de metileno.',
    posOp: 'Dexametasona obrigatória contra edema de glote. Adrenalina racêmica inalatória.',
    referencias: 'ASA Practice Advisory on Operating Room Fires.',
  },
  {
    especialidade: 'Otorrinolaringologia',
    nome: 'Rinoplastia e Otoplastia',
    tempos: '1. Infiltração local extensa; 2. Fraturas nasais ou ressecção de cartilagem auricular.',
    tecnica: 'Rino: Geral ou Sedação Profunda. Otoplastia: Local + MAC.',
    problemas: 'Sangramento/Equimose; Náuseas severas por deglutição de sangue.',
    correcoes: 'Ácido Tranexâmico IV (10–15 mg/kg) pré-incisão. Controle de PAM com Dexmedetomidina.',
    posOp: 'Deep Extubation é recomendada se via aérea favorável (evitar tosse). Risco hematoma retroauricular.',
    referencias: 'Daniel, Rhinoplasty Anesthetic Management.',
  },

  // ── NEUROCIRURGIA ─────────────────────────────────────────
  {
    especialidade: 'Neurocirurgia',
    nome: 'Craniotomia (Tumor, Aneurisma, Epilepsia)',
    tempos: '1. Pinos Mayfield; 2. Craniotomia; 3. Exérese tumoral ou Mapeamento por ECoG (Epilepsia).',
    tecnica: 'Geral TIVA (Propofol) é padrão. Na Epilepsia, usar MAC ou paralisar sedativos na fase de Mapeamento.',
    problemas: 'Hipertensão Intracraniana ("Tight Brain"); Ruptura de aneurisma; Crise convulsiva intra-op.',
    correcoes: 'Tight Brain: Manitol 20% / Salina 3%. Hiperventilação temporária. Crise no ECoG: Irrigar córtex com Soro Gelado.',
    posOp: 'UTI. Despertar neurocirúrgico precoce e sem tosse (para exame neurológico imediato).',
    referencias: 'Sharma et al., SNACC Guidelines. Ebrahim et al., Epilepsy Surgery.',
  },
  {
    especialidade: 'Neurocirurgia',
    nome: 'Embolização Endovascular de Aneurisma',
    tempos: '1. Acesso femoral/radial; 2. Cateterismo cerebral fluoroscópico; 3. Coils/Stents.',
    tecnica: 'Geral IOT obrigatória (imobilidade rigorosa para subtração digital).',
    problemas: 'Ruptura de aneurisma intra-op pelo cateter; Tromboembolismo; Ambiente hostil (radiologia).',
    correcoes: 'Ruptura: Hipotensão aguda + reversão com Protamina (1 mg/100 UI Heparina). Trombose: Tirofiban local.',
    posOp: 'Observar sítio de punção (hematoma retroperitoneal).',
    referencias: 'Raper et al., SNACC Endovascular Guidelines.',
  },
  {
    especialidade: 'Neurocirurgia',
    nome: 'Estimulação Cerebral Profunda (DBS)',
    tempos: '1. Halo estereotáxico; 2. Perfuração; 3. Microeletrodo no núcleo subtalâmico.',
    tecnica: 'Awake Craniotomy. Dexmedetomidina é a droga de escolha.',
    problemas: 'Propofol e GABAérgicos inibem leitura do núcleo alvo. Ansiedade extrema com crânio fixo.',
    correcoes: 'Manter PAS < 140 mmHg para evitar hematoma intracraniano no trajeto da agulha. Comunicação contínua.',
    posOp: 'Cefaleia pós-op. Internalização da bateria segue sob Geral.',
    referencias: 'Venkatraghavan et al., Anesthesia for DBS.',
  },
  {
    especialidade: 'Neurocirurgia',
    nome: 'Derivação Ventriculoperitoneal e ETV',
    tempos: 'DVP: Cateter crânio-abdome. ETV (Endoscópica): Perfuração do 3º ventrículo.',
    tecnica: 'Geral IOT. Evitar hipercapnia (risco de herniação por hidrocefalia prévia).',
    problemas: 'ETV: Reflexo de Cushing (bradicardia extrema/assistolia) ao perfurar o diencéfalo. DVP: Dor aguda do tunelizador.',
    correcoes: 'ETV: Pausar irrigação endoscópica imediatamente (reflexo autônomo passa rápido). Usar fluidos a 37 °C.',
    posOp: 'Diabetes insipidus transitório pós-ETV.',
    referencias: 'Schroeder et al., Endoscopic neurosurgery.',
  },
  {
    especialidade: 'Neurocirurgia',
    nome: 'Craniectomia Descompressiva (Trauma)',
    tempos: '1. Remoção de grande retalho ósseo; 2. Duroplastia de expansão.',
    tecnica: 'Emergência (TCE/AVC). TIVA ou Ketamina (segura no trauma para manter perfusão).',
    problemas: 'Choque hemorrágico associado; Tríade de Cushing (herniação iminente).',
    correcoes: 'Metas Hemodinâmicas (Brain Trauma Foundation): Manter PPC > 60 mmHg (Noradrenalina). Salina Hipertônica de resgate.',
    posOp: 'UTI 30 graus. Profilaxia de infecção.',
    referencias: 'Carney et al., Brain Trauma Foundation Guidelines.',
  },

  // ── GINECOLOGIA ───────────────────────────────────────────
  {
    especialidade: 'Ginecologia',
    nome: 'Histerectomia, Miomectomia e Ressecção de Endometriose',
    tempos: '1. Laparoscópica/Robótica/Aberta; 2. Ressecção com manipulação extensa pélvica.',
    tecnica: 'Geral IOT (TIVA) devido ao Trendelenburg e pneumoperitônio prolongado. Raqui para via vaginal.',
    problemas: 'Sangramento Maciço (Miomas hipervasculares); Efeitos da Vasopressina local (Crise hipertensiva); Dor crônica centralizada.',
    correcoes: 'Vasopressina máx 4–6 UI (aviso prévio, ter Nitroglicerina). Endometriose: uso de Ketamina/Dexmedetomidina intra-op para modular dor central (1A).',
    posOp: 'ERAS: TAP block/QL block guiado por USG substituiu a peridural torácica em laparotomias. Alta acelerada.',
    referencias: 'Nelson et al., ERAS Gynecologic/Oncology.',
  },
  {
    especialidade: 'Ginecologia',
    nome: 'Cirurgias Anexiais, Laqueadura e Bartholinectomia',
    tempos: '1. Ressecção ovariana/tubária laparoscópica ou Exérese de cisto vulvar.',
    tecnica: 'Geral com Máscara Laríngea (procedimentos < 1 h) ou Raquianestesia T4 (Laqueadura pós-parto).',
    problemas: 'Dor referida no ombro (escapulalgia por CO2 frênico). Abscesso de Bartholin agudo impede ação de anestesia local (pH baixo).',
    correcoes: 'Esvaziar abdome de CO2 sob manobra de recrutamento inspiratório ativo.',
    posOp: 'Alta no dia (Day-clinic). Analgesia multimodal oral.',
    referencias: 'SAMBA Guidelines.',
  },
  {
    especialidade: 'Ginecologia',
    nome: 'Histeroscopia Cirúrgica e Conização (CAF)',
    tempos: '1. Dilatação cervical; 2. Ressecção uterina com fluido sob pressão ou alça térmica no colo.',
    tecnica: 'Sedação (MAC) + Bloqueio Paracervical ou Raquianestesia curta.',
    problemas: 'Intoxicação Hídrica na Histeroscopia; Reflexo vagal e dor em queimação no CAF.',
    correcoes: 'Histeroscopia Bipolar usa Soro Fisiológico: limite de déficit 2.500 mL (pós isso, EAP). Glicina limite 1.000 mL.',
    posOp: 'AINEs para cólicas uterinas.',
    referencias: 'AAGL Guidelines Hysteroscopic Media.',
  },
  {
    especialidade: 'Ginecologia',
    nome: 'Colpoperineoplastia (Prolapso)',
    tempos: '1. Litotomia; 2. Incisão vaginal e plicatura de fáscias.',
    tecnica: 'Raquianestesia em sela (T10) provê relaxamento esfincteriano perineal absoluto.',
    problemas: 'Hemorragia de plexos pélvicos. Lesão isquêmica de nervos lombo-sacros (perneiras longas).',
    correcoes: 'Movimentar ambas as pernas simultaneamente nos estribos para evitar luxação sacroilíaca.',
    posOp: 'Retenção urinária pós-operatória. Paracetamol + Opioide fraco.',
    referencias: 'Ljungqvist et al., ERAS Pelvic Organ Prolapse.',
  },

  // ── OFTALMOLOGIA ──────────────────────────────────────────
  {
    especialidade: 'Oftalmologia',
    nome: 'Facoemulsificação, Refrativa e Exéreses (Pterígio/Calázio)',
    tempos: '1. Laser ou ultrassom sob campo visual restrito (microscópio).',
    tecnica: 'Tópica (Colírios) + Sedação Ultraleve (MAC). Calázio pediátrico: Geral curta.',
    problemas: 'Apneia seguida de sobressalto no microscópio (rompendo a cápsula do cristalino); Claustrofobia.',
    correcoes: 'Doses mínimas ("Less is more"). Fornecer O2 sob o campo cirúrgico para varrer o CO2.',
    posOp: 'Alta em minutos. Gelo local.',
    referencias: 'Kumar et al., Local anaesthesia for cataract.',
  },
  {
    especialidade: 'Oftalmologia',
    nome: 'Vitrectomia, Retinopexia e Trabeculectomia',
    tempos: '1. Acesso intraocular; 2. Peeling macular/injeção de gás ou buckle escleral.',
    tecnica: 'Bloqueio Peribulbar ou Geral. Controle estrito de PIO (Glaucoma).',
    problemas: 'Interação N2O-Gás letal; Reflexo Oculocardíaco (bradicardia); NVPO intensa.',
    correcoes: 'PROIBIÇÃO de N2O mín. 15 minutos antes da injeção de gás SF6/C3F8. Tratar bradicardia com alívio da tração e Atropina.',
    posOp: 'Face-down pós-op (Gás). Dor severa no Scleral Buckle (Cetorolaco IV).',
    referencias: 'Seaberg et al., Ophthalmic Surgery.',
  },
  {
    especialidade: 'Oftalmologia',
    nome: 'Transplante de Córnea e Dacriocistorrinostomia',
    tempos: '1. Trepanação ("Globo Aberto") ou osteotomia nasal.',
    tecnica: 'Geral IOT com controle absoluto de tosse. DCR exige tubo RAE.',
    problemas: 'Globo Aberto: Extubação com tosse gera Hemorragia Expulsiva Supracoroidal (cegueira). Sangramento nasal na DCR.',
    correcoes: 'Deep Extubation (plano profundo) ou Dexmedetomidina/Lidocaína garantem despertar "liso" e seguro. DCR requer tampão faríngeo.',
    posOp: 'Supino estrito. Prevenção de tosse e vômito obrigatória.',
    referencias: 'Guidelines for Perioperative Management of Open Globe.',
  },
  {
    especialidade: 'Oftalmologia',
    nome: 'Cirurgia de Estrabismo e Blefaroplastia',
    tempos: '1. Tração de músculos extraoculares ou excisão de gordura palpebral.',
    tecnica: 'Estrabismo: Geral (Pediatria). Blefaroplastia: Local + MAC.',
    problemas: 'Reflexo Oculocardíaco (ROC > 90% em estrabismo); Hematoma retrobulbar iatrogênico na blefaroplastia.',
    correcoes: 'Atropina profilática na indução pediátrica. Avaliar clinicamente sinais de tensão orbitária.',
    posOp: 'NVPO maciça no estrabismo (Profilaxia com Dexa+Ondansetrona).',
    referencias: 'Blanc et al., The Oculocardiac reflex.',
  },

  // ── CIRURGIA PLÁSTICA ─────────────────────────────────────
  {
    especialidade: 'Cirurgia Plástica',
    nome: 'Mamoplastia (Aumento, Redutora) e Ritidoplastia (Face)',
    tempos: '1. Incisão; 2. Descolamento SMAS/muscular; 3. Ressecção/Implantes.',
    tecnica: 'Geral TIVA obrigatória (melhor padrão para evitar NVPO).',
    problemas: 'Altíssima incidência NVPO; Dor submuscular peitoral; Hematoma de SMAS expandindo.',
    correcoes: 'PECS Block ecoguiado (Reduz 70% opioides 1A). Hipotensão permissiva controlada para hemostasia facial fina.',
    posOp: 'Prevenção tripla NVPO. Elevação da cabeceira no Lifting.',
    referencias: 'Blanco et al., The PECS block.',
  },
  {
    especialidade: 'Cirurgia Plástica',
    nome: 'Lipoaspiração, Abdominoplastia e Gluteoplastia (BBL)',
    tempos: '1. Infiltração Tumescente; 2. Aspiração; 3. Lipoenxertia glútea/Plicatura abdominal.',
    tecnica: 'Geral ou Peridural. Prevenção máxima contra TVP.',
    problemas: 'Embolia de Gordura Letal no BBL (intramuscular); Risco maciço de TEP (Abdominoplastia); LAST da lidocaína.',
    correcoes: 'Limite Lidocaína ASPS: 35 mg/kg. Lipoenxertia: APENAS subcutânea. Heparina profilática (Escore Caprini > 7).',
    posOp: 'TAP block para a plicatura muscular. Proibido sentar no BBL.',
    referencias: 'Mofid et al., ASERF Fat Grafting. ASPS VTE Task Force.',
  },
  {
    especialidade: 'Cirurgia Plástica',
    nome: 'Ninfoplastia, Ginecomastia e Otoplastia',
    tempos: '1. Excisão labial, glândula mamária ou cartilagem auricular.',
    tecnica: 'Local + Sedação MAC (Ambulatorial) ou Raquianestesia em sela (Ninfoplastia).',
    problemas: 'Dor por bloqueio insuficiente da glândula mamária (nervo intercostal profundo).',
    correcoes: 'Aguardar tempo de latência após infiltração profunda ou suportar com Alfentanil.',
    posOp: 'Day-clinic. Uso de cintas e capacete compressivo.',
    referencias: 'ASPS Practice Advisories.',
  },

  // ── CIRURGIA VASCULAR ─────────────────────────────────────
  {
    especialidade: 'Cirurgia Vascular',
    nome: 'Endarterectomia Carotídea e Bypass Periférico',
    tempos: '1. Clampeamento vascular e remoção de placa ateromatosa/derivação.',
    tecnica: 'Carótida: Regional Plexo Cervical ou Geral (GALA Trial). Bypass: Raquianestesia prolongada.',
    problemas: 'Isquemia Cerebral no clampe carotídeo; Risco extremo de IAM intra-op.',
    correcoes: 'Aumentar PAM > 20% no clampe carotídeo. Heparinização sistêmica guiada por TCA. Controle normotenso rigoroso no desclampeamento.',
    posOp: 'Unidade de AVC pós-Endarterectomia (risco hematoma cervical de via aérea).',
    referencias: 'GALA Trial. AHA/ACC Perioperative Guidelines.',
  },
  {
    especialidade: 'Cirurgia Vascular',
    nome: 'Reparo Aneurisma de Aorta (Aberta/EVAR)',
    tempos: '1. Laparotomia retroperitoneal (Aberta) ou acesso femoral escópico (EVAR).',
    tecnica: 'Aberta: Geral + Peridural torácica baixa. EVAR: MAC ou Raqui.',
    problemas: 'Choque de Desclampeamento Aórtico (vasodilatação isquêmica aguda); Nefropatia por contraste.',
    correcoes: 'Soltar clamp aórtico lentamente; Bólus de Cálcio, Vasopressor e volume preparados. Hidratação para contraste.',
    posOp: 'Extubação precoce alvo ERAS. Monitorar MMII.',
    referencias: 'SVS Practice Guidelines AAA.',
  },
  {
    especialidade: 'Cirurgia Vascular',
    nome: 'Trombectomia/Embolectomia (Fogarty) e Amputação Maior',
    tempos: 'Emergência (Salvamento). Passagem de cateter Fogarty intrarterial ou osteotomia transfemoral.',
    tecnica: 'Raqui, Local ou Geral (depende urgência). Amputação: Bloqueios Nervosos (Isquiático/Femoral).',
    problemas: 'Síndrome de Reperfusão letal (Potássio e mioglobina no coração na desobstrução). Dor do Membro Fantasma.',
    correcoes: 'Ketamina intra-op e Cateter Contínuo reduzem Dor Fantasma (1B). Bicarbonato/Cálcio profilático antes da reperfusão.',
    posOp: 'UTI. Fasciotomia frequente por Síndrome Compartimental no reperfundido.',
    referencias: 'ASRA Pain Medicine Guidelines.',
  },
  {
    especialidade: 'Cirurgia Vascular',
    nome: 'Fístula Arteriovenosa, Varizes, Filtro de Veia Cava e Angioplastia',
    tempos: '1. Termoablação a Laser (Varizes), Anastomose de FAV, implante endovascular.',
    tecnica: 'Varizes: Tumescente Pura. FAV: Bloqueio Supraclavicular ecoguiado.',
    problemas: 'Queimadura de Laser (nervo safeno); DRC hipercalêmica na FAV; Falência respiratória no Filtro de VCI.',
    correcoes: 'Bloqueio de Plexo gera simpatectomia e vasodilatação que garante maturidade da FAV (Nível 1A).',
    posOp: 'Ambulatorial. Proteger FAV de punções venosas na enfermaria.',
    referencias: 'KDOQI Vascular Access Guidelines.',
  },
];
